package cs319.group1e.procheck319;

import javax.swing.*;
import java.awt.*;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author bedir
 */
public class GroupGUI extends javax.swing.JFrame {

    private Student currentUser;
    private GroupRepository groupRepository;
    private ClassRepository classRepository;
    private StudentRepository studentRepository;
    private String goTo;
    private int peer;
    private int artifactReviewId;
    private Submission sub;


    /**
     * Creates new form procheckGUI
     */
    public GroupGUI(StudentRepository studentRepository,  GroupRepository groupRepository, ClassRepository classRepository) {
        this.groupRepository = groupRepository;
        this.classRepository = classRepository;
        this.studentRepository = studentRepository;
        initComponents();
    }

    public void setSub(Submission sub){
        this.sub = sub;
    }
    public Submission getSub(){
        return sub;
    }
    public void setCurrentUser(Student currentUser) {
        this.currentUser = currentUser;
    }

    public int getPeer() {
        return peer;
    }
    public void setPeer(int peer) {
        this.peer = peer;
    }

    public Student getCurrentUser() {
        return currentUser;
    }

    public int getArtifactReviewId() {
        return artifactReviewId;
    }
    public void setArtifactReviewId(int artifactReviewId) {
        this.artifactReviewId = artifactReviewId;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        overallProgressPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        groupMemberPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        groupMemberLabel5 = new javax.swing.JLabel();
        groupMemberLabel1 = new javax.swing.JLabel();
        groupMemberLabel2 = new javax.swing.JLabel();
        groupMemberLabel3 = new javax.swing.JLabel();
        groupMemberLabel4 = new javax.swing.JLabel();
        groupMemberButton1 = new javax.swing.JButton();
        groupMemberButton2 = new javax.swing.JButton();
        groupMemberButton3 = new javax.swing.JButton();
        groupMemberButton4 = new javax.swing.JButton();
        groupMemberButton5 = new javax.swing.JButton();
        projectSummaryPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        headerPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        launchDatePanel = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        otherGroupsPanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        otherGroupsLabel1 = new javax.swing.JLabel();
        groupButton1 = new javax.swing.JButton();
        otherGroupsLabel4 = new javax.swing.JLabel();
        groupButton2 = new javax.swing.JButton();
        otherGroupsLabel2 = new javax.swing.JLabel();
        groupButton3 = new javax.swing.JButton();
        otherGroupsLabel3 = new javax.swing.JLabel();
        otherGroupsLabel7 = new javax.swing.JLabel();
        otherGroupsLabel5 = new javax.swing.JLabel();
        otherGroupsLabel8 = new javax.swing.JLabel();
        otherGroupsLabel10 = new javax.swing.JLabel();
        otherGroupsLabel6 = new javax.swing.JLabel();
        otherGroupsLabel11 = new javax.swing.JLabel();
        otherGroupsLabel9 = new javax.swing.JLabel();
        groupButton5 = new javax.swing.JButton();
        groupButton6 = new javax.swing.JButton();
        groupButton7 = new javax.swing.JButton();
        groupButton4 = new javax.swing.JButton();
        groupButton11 = new javax.swing.JButton();
        groupButton8 = new javax.swing.JButton();
        groupButton9 = new javax.swing.JButton();
        groupButton10 = new javax.swing.JButton();
        calendarPanel = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        statisticsPanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        viewReviewLabel3 = new javax.swing.JLabel();
        viewARButton1 = new javax.swing.JButton();
        viewFeedbackButton1 = new javax.swing.JButton();
        viewReviewLabel1 = new javax.swing.JLabel();
        viewReviewLabel2 = new javax.swing.JLabel();
        viewReviewLabel4 = new javax.swing.JLabel();
        viewReviewLabel5 = new javax.swing.JLabel();
        viewARButton5 = new javax.swing.JButton();
        viewFeedbackButton5 = new javax.swing.JButton();
        viewARButton2 = new javax.swing.JButton();
        viewFeedbackButton2 = new javax.swing.JButton();
        viewARButton3 = new javax.swing.JButton();
        viewFeedbackButton3 = new javax.swing.JButton();
        viewARButton4 = new javax.swing.JButton();
        viewFeedbackButton4 = new javax.swing.JButton();
        announcementsPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        deadlinesPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        upcomingDeadlinesLabel5 = new javax.swing.JLabel();
        upcomingDeadlinesLabel3 = new javax.swing.JLabel();
        upcomingDeadlinesLabel4 = new javax.swing.JLabel();
        upcomingDeadlinesLabel6 = new javax.swing.JLabel();
        upcomingDeadlinesLabel1 = new javax.swing.JLabel();
        upcomingDeadlinesLabel2 = new javax.swing.JLabel();
        submitButton2 = new javax.swing.JButton();
        submitButton1 = new javax.swing.JButton();
        submitButton4 = new javax.swing.JButton();
        submitButton5 = new javax.swing.JButton();
        submitButton6 = new javax.swing.JButton();
        submitButton3 = new javax.swing.JButton();
        requestLabel1 = new javax.swing.JLabel();
        acceptButton1 = new javax.swing.JButton();

        overallProgressPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        groupMemberPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        groupMemberLabel5 = new javax.swing.JLabel();
        groupMemberLabel1 = new javax.swing.JLabel();
        groupMemberLabel2 = new javax.swing.JLabel();
        groupMemberLabel3 = new javax.swing.JLabel();
        groupMemberLabel4 = new javax.swing.JLabel();
        groupMemberButton1 = new javax.swing.JButton();
        groupMemberButton2 = new javax.swing.JButton();
        groupMemberButton3 = new javax.swing.JButton();
        groupMemberButton4 = new javax.swing.JButton();
        groupMemberButton5 = new javax.swing.JButton();
        projectSummaryPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        headerPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        launchDatePanel = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        otherGroupsPanel = new javax.swing.JPanel();
        artifactReviewMainLabel = new javax.swing.JLabel();
        randomArtifactButton = new javax.swing.JButton();
        artifactReviewURLLabel = new javax.swing.JLabel();
        artifactURLField = new javax.swing.JTextField();
        artifactReviewLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        artifactReviewArea = new javax.swing.JTextArea();
        firstArtifactCheckBox = new javax.swing.JCheckBox();
        secondArtifactCheckBox = new javax.swing.JCheckBox();
        submitArtifactButton = new javax.swing.JButton();
        calendarPanel = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        requestLabel1 = new javax.swing.JLabel();
        acceptButton1 = new javax.swing.JButton();
        rejectButton1 = new javax.swing.JButton();
        requestLabel2 = new javax.swing.JLabel();
        acceptButton2 = new javax.swing.JButton();
        rejectButton2 = new javax.swing.JButton();
        requestLabel3 = new javax.swing.JLabel();
        acceptButton3 = new javax.swing.JButton();
        rejectButton3 = new javax.swing.JButton();
        requestLabel4 = new javax.swing.JLabel();
        acceptButton4 = new javax.swing.JButton();
        rejectButton4 = new javax.swing.JButton();
        statisticsPanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        viewReviewLabel3 = new javax.swing.JLabel();
        viewARButton1 = new javax.swing.JButton();
        viewFeedbackButton1 = new javax.swing.JButton();
        viewReviewLabel1 = new javax.swing.JLabel();
        viewReviewLabel2 = new javax.swing.JLabel();
        viewReviewLabel4 = new javax.swing.JLabel();
        viewReviewLabel5 = new javax.swing.JLabel();
        viewARButton5 = new javax.swing.JButton();
        viewFeedbackButton5 = new javax.swing.JButton();
        viewARButton2 = new javax.swing.JButton();
        viewFeedbackButton2 = new javax.swing.JButton();
        viewARButton3 = new javax.swing.JButton();
        viewFeedbackButton3 = new javax.swing.JButton();
        viewARButton4 = new javax.swing.JButton();
        viewFeedbackButton4 = new javax.swing.JButton();
        announcementsPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        deadlinesPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        upcomingDeadlinesLabel5 = new javax.swing.JLabel();
        upcomingDeadlinesLabel3 = new javax.swing.JLabel();
        upcomingDeadlinesLabel4 = new javax.swing.JLabel();
        upcomingDeadlinesLabel6 = new javax.swing.JLabel();
        upcomingDeadlinesLabel1 = new javax.swing.JLabel();
        upcomingDeadlinesLabel2 = new javax.swing.JLabel();
        submitButton2 = new javax.swing.JButton();
        submitButton1 = new javax.swing.JButton();
        submitButton4 = new javax.swing.JButton();
        submitButton5 = new javax.swing.JButton();
        submitButton6 = new javax.swing.JButton();
        submitButton3 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();


        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        overallProgressPanel.setBackground(new java.awt.Color(232, 235, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Overall Progress");

        javax.swing.GroupLayout overallProgressPanelLayout = new javax.swing.GroupLayout(overallProgressPanel);
        overallProgressPanel.setLayout(overallProgressPanelLayout);
        overallProgressPanelLayout.setHorizontalGroup(
                overallProgressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, overallProgressPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                                .addContainerGap())
        );
        overallProgressPanelLayout.setVerticalGroup(
                overallProgressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(overallProgressPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        groupMemberPanel.setBackground(new java.awt.Color(232, 235, 255));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Group Members");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        groupMemberLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        groupMemberLabel5.setText("jLabel24");

        groupMemberLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        groupMemberLabel1.setText("jLabel24");

        groupMemberLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        groupMemberLabel2.setText("jLabel24");

        groupMemberLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        groupMemberLabel3.setText("jLabel24");

        groupMemberLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        groupMemberLabel4.setText("jLabel24");

        groupMemberButton1.setBackground(new java.awt.Color(120, 88, 161));
        groupMemberButton1.setForeground(new java.awt.Color(255, 255, 255));
        groupMemberButton1.setText("Review Peer");
        groupMemberButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                groupMemberButton1ActionPerformed(evt);
            }
        });

        groupMemberButton2.setBackground(new java.awt.Color(120, 88, 161));
        groupMemberButton2.setForeground(new java.awt.Color(255, 255, 255));
        groupMemberButton2.setText("Review Peer");
        groupMemberButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                groupMemberButton2ActionPerformed(evt);
            }
        });

        groupMemberButton3.setBackground(new java.awt.Color(120, 88, 161));
        groupMemberButton3.setForeground(new java.awt.Color(255, 255, 255));
        groupMemberButton3.setText("Review Peer");
        groupMemberButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                groupMemberButton3ActionPerformed(evt);
            }
        });

        groupMemberButton4.setBackground(new java.awt.Color(120, 88, 161));
        groupMemberButton4.setForeground(new java.awt.Color(255, 255, 255));
        groupMemberButton4.setText("Review Peer");
        groupMemberButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
               groupMemberButton4ActionPerformed(evt);
            }
        });

        groupMemberButton5.setBackground(new java.awt.Color(120, 88, 161));
        groupMemberButton5.setForeground(new java.awt.Color(255, 255, 255));
        groupMemberButton5.setText("Review Peer");
        groupMemberButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                groupMemberButton5ActionPerformed(evt);
            }
        });
        javax.swing.GroupLayout groupMemberPanelLayout = new javax.swing.GroupLayout(groupMemberPanel);
        groupMemberPanel.setLayout(groupMemberPanelLayout);
        groupMemberPanelLayout.setHorizontalGroup(
                groupMemberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(groupMemberPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(groupMemberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(groupMemberPanelLayout.createSequentialGroup()
                                                .addComponent(groupMemberLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE))
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                                        .addGroup(groupMemberPanelLayout.createSequentialGroup()
                                                .addGroup(groupMemberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(groupMemberLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(groupMemberLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(groupMemberLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(groupMemberLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(68, 68, 68)
                                                .addGroup(groupMemberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(groupMemberButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(groupMemberButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(groupMemberButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(groupMemberButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(groupMemberButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
        );
        groupMemberPanelLayout.setVerticalGroup(
                groupMemberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(groupMemberPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(groupMemberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(groupMemberButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(groupMemberLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(groupMemberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(groupMemberLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                        .addComponent(groupMemberButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(groupMemberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(groupMemberButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(groupMemberPanelLayout.createSequentialGroup()
                                                .addGap(29, 29, 29)
                                                .addComponent(jLabel4))
                                        .addComponent(groupMemberLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(groupMemberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(groupMemberButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(groupMemberLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(groupMemberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(groupMemberLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(groupMemberButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                                .addGap(55, 55, 55))
        );

        projectSummaryPanel.setBackground(new java.awt.Color(232, 235, 255));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Project Summary");

        javax.swing.GroupLayout projectSummaryPanelLayout = new javax.swing.GroupLayout(projectSummaryPanel);
        projectSummaryPanel.setLayout(projectSummaryPanelLayout);
        projectSummaryPanelLayout.setHorizontalGroup(
                projectSummaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(projectSummaryPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );
        projectSummaryPanelLayout.setVerticalGroup(
                projectSummaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(projectSummaryPanelLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel5)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        headerPanel.setBackground(new java.awt.Color(232, 235, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Assignment Process");

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
                headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(headerPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1292, Short.MAX_VALUE))
        );
        headerPanelLayout.setVerticalGroup(
                headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(headerPanelLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 0, Short.MAX_VALUE))
        );

        launchDatePanel.setBackground(new java.awt.Color(232, 235, 255));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Projected Launch Date");

        javax.swing.GroupLayout launchDatePanelLayout = new javax.swing.GroupLayout(launchDatePanel);
        launchDatePanel.setLayout(launchDatePanelLayout);
        launchDatePanelLayout.setHorizontalGroup(
                launchDatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(launchDatePanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                                .addContainerGap())
        );
        launchDatePanelLayout.setVerticalGroup(
                launchDatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(launchDatePanelLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel10)
                                .addContainerGap(109, Short.MAX_VALUE))
        );

        //****************************************************************************

        //OLD VERSION PART

        //***********************************************************************************

        //ARTIFACT REVIEW PANEL --> OLD otherGroupsPanel
        otherGroupsPanel.setBackground(new java.awt.Color(232, 235, 255));

        artifactReviewMainLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        artifactReviewMainLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        artifactReviewMainLabel.setText("Artifact Review");

        randomArtifactButton.setBackground(new java.awt.Color(120, 88, 161));
        randomArtifactButton.setForeground(new java.awt.Color(255, 255, 255));
        randomArtifactButton.setText("Review Random Artifact");
        randomArtifactButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                randomArtifactButtonActionPerformed(evt);
            }
        });

        artifactReviewURLLabel.setText("URL: ");

        artifactURLField.setEditable(false);
        artifactURLField.setText("Press \"Review Random Artifact\" Button First");

        artifactReviewLabel.setText("Write Your Feedback: ");

        artifactReviewArea.setColumns(20);
        artifactReviewArea.setRows(5);
        artifactReviewArea.setEnabled(false);
        jScrollPane1.setViewportView(artifactReviewArea);

        firstArtifactCheckBox.setText("First Artifact Review State");
        firstArtifactCheckBox.setEnabled(false);

        secondArtifactCheckBox.setText("Second Artifact Review State");
        secondArtifactCheckBox.setEnabled(false);

        submitArtifactButton.setBackground(new java.awt.Color(120, 88, 161));
        submitArtifactButton.setForeground(new java.awt.Color(255, 255, 255));
        submitArtifactButton.setText("Submit Review");
        submitArtifactButton.setEnabled(false);
        submitArtifactButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitArtifactButtonActionPerformed(evt);
            }
        });

        //*****************************************************************************
        javax.swing.GroupLayout otherGroupsPanelLayout = new javax.swing.GroupLayout(otherGroupsPanel);
        otherGroupsPanel.setLayout(otherGroupsPanelLayout);
        otherGroupsPanelLayout.setHorizontalGroup(
                otherGroupsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(otherGroupsPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(otherGroupsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(otherGroupsPanelLayout.createSequentialGroup()
                                                .addGroup(otherGroupsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(artifactReviewMainLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addGroup(otherGroupsPanelLayout.createSequentialGroup()
                                                                .addComponent(artifactReviewURLLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(artifactURLField))
                                                        .addGroup(otherGroupsPanelLayout.createSequentialGroup()
                                                                .addGroup(otherGroupsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                        .addComponent(firstArtifactCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(artifactReviewLabel)
                                                                        .addComponent(secondArtifactCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                                .addGap(0, 134, Short.MAX_VALUE)))
                                                .addContainerGap())
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, otherGroupsPanelLayout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(randomArtifactButton, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(45, 45, 45))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, otherGroupsPanelLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(submitArtifactButton, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21))
        );
        otherGroupsPanelLayout.setVerticalGroup(
                otherGroupsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(otherGroupsPanelLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(artifactReviewMainLabel)
                                .addGap(18, 18, 18)
                                .addComponent(randomArtifactButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(otherGroupsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(artifactReviewURLLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(artifactURLField, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(artifactReviewLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(firstArtifactCheckBox)
                                .addGap(18, 18, 18)
                                .addComponent(secondArtifactCheckBox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(submitArtifactButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36))
        );


        //REQUEST PANEL
        calendarPanel.setBackground(new java.awt.Color(232, 235, 255));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Requests");

        requestLabel1.setText("Student's Request Can Be Seen From Here ------->");

        acceptButton1.setBackground(new java.awt.Color(120, 88, 161));
        acceptButton1.setForeground(new java.awt.Color(255, 255, 255));
        acceptButton1.setText("View Request");
        acceptButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout calendarPanelLayout = new javax.swing.GroupLayout(calendarPanel);
        calendarPanel.setLayout(calendarPanelLayout);
        calendarPanelLayout.setHorizontalGroup(
                calendarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(calendarPanelLayout.createSequentialGroup()
                                .addGap(131, 131, 131)
                                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                                .addGap(137, 137, 137))
                        .addGroup(calendarPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(calendarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(requestLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(calendarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(acceptButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        )
                                .addGap(18, 18, 18)
                                .addGroup(calendarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        calendarPanelLayout.setVerticalGroup(
                calendarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(calendarPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addGroup(calendarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(requestLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(acceptButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(calendarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)

                                        )
                                .addGap(18, 18, 18)
                                .addGroup(calendarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)

                                        )
                                .addGap(18, 18, 18)
                                .addGroup(calendarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        )
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        statisticsPanel.setBackground(new java.awt.Color(232, 235, 255));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("View Reviews");

        viewReviewLabel3.setText("jLabel30");

        viewARButton1.setBackground(new java.awt.Color(120, 88, 161));
        viewARButton1.setForeground(new java.awt.Color(255, 255, 255));
        viewARButton1.setText("View Artifact Review");
        viewARButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
              viewARButton1ActionPerformed(evt);
            }
        });

        viewFeedbackButton1.setBackground(new java.awt.Color(120, 88, 161));
        viewFeedbackButton1.setForeground(new java.awt.Color(255, 255, 255));
        viewFeedbackButton1.setText("View Feedback");
        viewFeedbackButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewFeedbackButton1ActionPerformed(evt);
            }
        });

        viewReviewLabel1.setText("jLabel30");

        viewReviewLabel2.setText("jLabel30");

        viewReviewLabel4.setText("jLabel30");

        viewReviewLabel5.setText("jLabel30");

        viewARButton5.setBackground(new java.awt.Color(120, 88, 161));
        viewARButton5.setForeground(new java.awt.Color(255, 255, 255));
        viewARButton5.setText("View Artifact Review");
        viewARButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewARButton5ActionPerformed(evt);
            }
        });

        viewFeedbackButton5.setBackground(new java.awt.Color(120, 88, 161));
        viewFeedbackButton5.setForeground(new java.awt.Color(255, 255, 255));
        viewFeedbackButton5.setText("View Feedback");
        viewFeedbackButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewFeedbackButton5ActionPerformed(evt);
            }
        });


        viewARButton2.setBackground(new java.awt.Color(120, 88, 161));
        viewARButton2.setForeground(new java.awt.Color(255, 255, 255));
        viewARButton2.setText("View Artifact Review");
        viewARButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewARButton2ActionPerformed(evt);
            }
        });

        viewFeedbackButton2.setBackground(new java.awt.Color(120, 88, 161));
        viewFeedbackButton2.setForeground(new java.awt.Color(255, 255, 255));
        viewFeedbackButton2.setText("View Feedback");
        viewFeedbackButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewFeedbackButton2ActionPerformed(evt);
            }
        });

        viewARButton3.setBackground(new java.awt.Color(120, 88, 161));
        viewARButton3.setForeground(new java.awt.Color(255, 255, 255));
        viewARButton3.setText("View Artifact Review");
        viewARButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewARButton3ActionPerformed(evt);
            }
        });

        viewFeedbackButton3.setBackground(new java.awt.Color(120, 88, 161));
        viewFeedbackButton3.setForeground(new java.awt.Color(255, 255, 255));
        viewFeedbackButton3.setText("View Feedback");
        viewFeedbackButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewFeedbackButton3ActionPerformed(evt);
            }
        });

        viewARButton4.setBackground(new java.awt.Color(120, 88, 161));
        viewARButton4.setForeground(new java.awt.Color(255, 255, 255));
        viewARButton4.setText("View Artifact Review");
        viewARButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewARButton4ActionPerformed(evt);
            }
        });

        viewFeedbackButton4.setBackground(new java.awt.Color(120, 88, 161));
        viewFeedbackButton4.setForeground(new java.awt.Color(255, 255, 255));
        viewFeedbackButton4.setText("View Feedback");
        viewFeedbackButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewFeedbackButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout statisticsPanelLayout = new javax.swing.GroupLayout(statisticsPanel);
        statisticsPanel.setLayout(statisticsPanelLayout);
        statisticsPanelLayout.setHorizontalGroup(
                statisticsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(statisticsPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(statisticsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(statisticsPanelLayout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addGroup(statisticsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(statisticsPanelLayout.createSequentialGroup()
                                                                .addGroup(statisticsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                        .addComponent(viewReviewLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                                                                        .addComponent(viewReviewLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addGroup(statisticsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                        .addComponent(viewARButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                                                                        .addComponent(viewARButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(statisticsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(statisticsPanelLayout.createSequentialGroup()
                                                                                .addComponent(viewFeedbackButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(0, 0, Short.MAX_VALUE))
                                                                        .addComponent(viewFeedbackButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                                        .addGroup(statisticsPanelLayout.createSequentialGroup()
                                                                .addGroup(statisticsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                        .addComponent(viewReviewLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                                                                        .addComponent(viewReviewLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(viewReviewLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addGroup(statisticsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                        .addComponent(viewARButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                                                                        .addComponent(viewARButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(viewARButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addGroup(statisticsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                        .addComponent(viewFeedbackButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                                                                        .addComponent(viewFeedbackButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(viewFeedbackButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                                .addContainerGap())
        );
        statisticsPanelLayout.setVerticalGroup(
                statisticsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(statisticsPanelLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addGroup(statisticsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(viewFeedbackButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(viewARButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(viewReviewLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(statisticsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(viewReviewLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(viewARButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(viewFeedbackButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(statisticsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(viewReviewLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(viewARButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(viewFeedbackButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(statisticsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(viewReviewLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(viewARButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(viewFeedbackButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(17, 17, 17)
                                .addGroup(statisticsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(viewReviewLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(viewARButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(viewFeedbackButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28))
        );

        announcementsPanel.setBackground(new java.awt.Color(232, 235, 255));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Announcements");

        javax.swing.GroupLayout announcementsPanelLayout = new javax.swing.GroupLayout(announcementsPanel);
        announcementsPanel.setLayout(announcementsPanelLayout);
        announcementsPanelLayout.setHorizontalGroup(
                announcementsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(announcementsPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE)
                                .addContainerGap())
        );
        announcementsPanelLayout.setVerticalGroup(
                announcementsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(announcementsPanelLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel6)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        deadlinesPanel.setBackground(new java.awt.Color(232, 235, 255));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Upcoming Deadlines");

        List<Assignment> assignments =classRepository.findByClassId(319).getProject().getAssignmentList();

        upcomingDeadlinesLabel5.setText(assignments.get(4).getTitle());

        upcomingDeadlinesLabel3.setText(assignments.get(3).getTitle());

        upcomingDeadlinesLabel4.setText(assignments.get(2).getTitle());

        upcomingDeadlinesLabel1.setText(assignments.get(1).getTitle());

        upcomingDeadlinesLabel2.setText(assignments.get(0).getTitle());

        submitButton2.setBackground(new java.awt.Color(120, 88, 161));
        submitButton2.setForeground(new java.awt.Color(255, 255, 255));
        submitButton2.setText("Make Submission");
        submitButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButton2ActionPerformed(evt);
            }
        });

        submitButton1.setBackground(new java.awt.Color(120, 88, 161));
        submitButton1.setForeground(new java.awt.Color(255, 255, 255));
        submitButton1.setText("Make Submission");
        submitButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButton1ActionPerformed(evt);
            }
        });

        submitButton4.setBackground(new java.awt.Color(120, 88, 161));
        submitButton4.setForeground(new java.awt.Color(255, 255, 255));
        submitButton4.setText("Make Submission");
        submitButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButton4ActionPerformed(evt);
            }
        });

        submitButton5.setBackground(new java.awt.Color(120, 88, 161));
        submitButton5.setForeground(new java.awt.Color(255, 255, 255));
        submitButton5.setText("Make Submission");
        submitButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButton5ActionPerformed(evt);
            }
        });

        submitButton3.setBackground(new java.awt.Color(120, 88, 161));
        submitButton3.setForeground(new java.awt.Color(255, 255, 255));
        submitButton3.setText("Make Submission");
        submitButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButton3ActionPerformed(evt);
            }
        });

        jTextField1.setText("Submission Link");

        javax.swing.GroupLayout deadlinesPanelLayout = new javax.swing.GroupLayout(deadlinesPanel);
        deadlinesPanel.setLayout(deadlinesPanelLayout);
        deadlinesPanelLayout.setHorizontalGroup(
                deadlinesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deadlinesPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(deadlinesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jTextField1)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, deadlinesPanelLayout.createSequentialGroup()
                                                .addGroup(deadlinesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(upcomingDeadlinesLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(upcomingDeadlinesLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(upcomingDeadlinesLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(upcomingDeadlinesLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                                                        .addComponent(upcomingDeadlinesLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(deadlinesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(submitButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
                                                        .addComponent(submitButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(submitButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(submitButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(submitButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addContainerGap())
        );
        deadlinesPanelLayout.setVerticalGroup(
                deadlinesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(deadlinesPanelLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(deadlinesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(upcomingDeadlinesLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(submitButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(4, 4, 4)
                                .addGroup(deadlinesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(upcomingDeadlinesLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(submitButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(deadlinesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(upcomingDeadlinesLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(submitButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(deadlinesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(upcomingDeadlinesLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(submitButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(deadlinesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(upcomingDeadlinesLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(submitButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(overallProgressPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(18, 18, 18)
                                                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(projectSummaryPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(groupMemberPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                .addComponent(calendarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(statisticsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                .addComponent(announcementsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(deadlinesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(otherGroupsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(launchDatePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(launchDatePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(overallProgressPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(groupMemberPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(statisticsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(calendarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(projectSummaryPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(announcementsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(deadlinesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(otherGroupsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //REQUEST ACCEPT OR REJECT
    private void acceptButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_groupButton11ActionPerformed
        Group g = groupRepository.findByGroupId(currentUser.getGroupId());
        Class c = classRepository.findByClassId(319);
        Request request = new Request(g.getGroupId(), g.getRequests().get(0).getSenderStudentId());
        String info = "";
        if(request != null) {
            int studentId = request.getSenderStudentId();
            Student student = studentRepository.findByUserId(studentId);
            info = student.getUserName() + " " + student.getUserSurname() + " has send request to join your group";
            UIManager um = new UIManager();
            um.put("OptionPane.background", new Color(120, 88, 161));
            um.put("Panel.background", new Color(120, 88, 161));
            int result = JOptionPane.showConfirmDialog(null,info, "Join Request",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE);

            //Accept request
            if(result == JOptionPane.YES_OPTION) {
                g.addGroupMember(student);
                g.getRequests().remove(0);
                studentRepository.save(student);
                groupRepository.save(g);
                classRepository.save(c);
            }else{
                g.getRequests().remove(0);
                groupRepository.save(g);
                classRepository.save(c);
            }
        }

    }

    //GET A RANDOM ARTIFACT BY PRESSING THE BUTTON!!!!!!!!!!!!!!!!
    private void randomArtifactButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_groupButton1ActionPerformed
        List<Assignment> assignments = new ArrayList<>();
        Group g = groupRepository.findByGroupId(currentUser.getGroupId());
        assignments = groupRepository.findByGroupId(currentUser.getGroupId()).getGroupAssignmentList();
        this.sub = currentUser.getRandomArtifact(assignments,g);
        String url = sub.getUrl();
        artifactURLField.setEditable(false);
        artifactURLField.setText(url);
        artifactReviewArea.setEnabled(true);
        firstArtifactCheckBox.setSelected(true);
    }

    //SUBMIT THE JTEXTFIELD TO THE SYSTEM!!!!!!!!!!!
    private void submitArtifactButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_groupButton1ActionPerformed
        String context = artifactReviewArea.getText();
        currentUser.reviewArtifact(sub,context);
        Class c = classRepository.findByClassId(319);
    }


    public String getGoTo() {
        return goTo;
    }

    public void setGoTo(String goTo) {
        this.goTo = goTo;
    }

    private void viewARButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_groupButton1ActionPerformed
        Submission s = groupRepository.findByGroupId(currentUser.getGroupId()).getGroupSubmissionList().get(0);
        List<ArtifactReview> reviews = groupRepository.findByGroupId(currentUser.getGroupId()).showArtifactReviewsDoneByOthers(s);

    }

    private void viewFeedbackButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_groupButton1ActionPerformed
        Submission s = groupRepository.findByGroupId(currentUser.getGroupId()).getGroupSubmissionList().get(0);
        InstructorFeedback feedback = s.getFeedback();
        double grade = s.getGrade();
    }

    private void viewARButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_groupButton1ActionPerformed
        Submission s = groupRepository.findByGroupId(currentUser.getGroupId()).getGroupSubmissionList().get(1);
        List<ArtifactReview> reviews = groupRepository.findByGroupId(currentUser.getGroupId()).showArtifactReviewsDoneByOthers(s);
    }

    private void viewFeedbackButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_groupButton1ActionPerformed
        Submission s = groupRepository.findByGroupId(currentUser.getGroupId()).getGroupSubmissionList().get(1);
        InstructorFeedback feedback = s.getFeedback();
        double grade = s.getGrade();
    }

    private void viewARButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_groupButton1ActionPerformed
        Submission s = groupRepository.findByGroupId(currentUser.getGroupId()).getGroupSubmissionList().get(2);
        List<ArtifactReview> reviews = groupRepository.findByGroupId(currentUser.getGroupId()).showArtifactReviewsDoneByOthers(s);
    }

    private void viewFeedbackButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_groupButton1ActionPerformed
        Submission s = groupRepository.findByGroupId(currentUser.getGroupId()).getGroupSubmissionList().get(2);
        InstructorFeedback feedback = s.getFeedback();
        double grade = s.getGrade();
    }

    private void viewARButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_groupButton1ActionPerformed
        Submission s = groupRepository.findByGroupId(currentUser.getGroupId()).getGroupSubmissionList().get(3);
        List<ArtifactReview> reviews = groupRepository.findByGroupId(currentUser.getGroupId()).showArtifactReviewsDoneByOthers(s);
    }

    private void viewFeedbackButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_groupButton1ActionPerformed
        Submission s = groupRepository.findByGroupId(currentUser.getGroupId()).getGroupSubmissionList().get(3);
        InstructorFeedback feedback = s.getFeedback();
        double grade = s.getGrade();
    }

    private void viewARButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_groupButton1ActionPerformed
        Submission s = groupRepository.findByGroupId(currentUser.getGroupId()).getGroupSubmissionList().get(4);
        List<ArtifactReview> reviews = groupRepository.findByGroupId(currentUser.getGroupId()).showArtifactReviewsDoneByOthers(s);
    }

    private void viewFeedbackButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_groupButton1ActionPerformed
        Submission s = groupRepository.findByGroupId(currentUser.getGroupId()).getGroupSubmissionList().get(4);
        InstructorFeedback feedback = s.getFeedback();
        double grade = s.getGrade();
    }


    private void submitButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_groupButton1ActionPerformed
        //POP UP FIFTH SUBMISSON PAGE WITH GITHUB LINK FIELD
        Assignment assignment = classRepository.findByClassId(319).getProject().getAssignmentList().get(0);
        String context = jTextField1.getText();
        Class c = classRepository.findByClassId(319);
        Submission submission = new Submission(assignment,context);
        c.getProject().getAssignmentList().get(0).addSubmission(submission);
        Group group = groupRepository.findByGroupId(currentUser.getGroupId());
        currentUser.addSubmission(submission,assignment,group);
        Student s = studentRepository.findByUserId(currentUser.getUserId());
        studentRepository.save(s);
        groupRepository.save(group);
        classRepository.save(c);
    }

    private void submitButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_groupButton1ActionPerformed
        //POP UP FIRST SUBMISSON PAGE WITH GITHUB LINK FIELD
        Assignment assignment = classRepository.findByClassId(319).getProject().getAssignmentList().get(1);
        String context = jTextField1.getText();
        Class c = classRepository.findByClassId(319);
        Submission submission = new Submission(assignment,context);
        c.getProject().getAssignmentList().get(1).addSubmission(submission);
        Group group = groupRepository.findByGroupId(currentUser.getGroupId());
        currentUser.addSubmission(submission,assignment,group);
        Student s = studentRepository.findByUserId(currentUser.getUserId());
        studentRepository.save(s);
        groupRepository.save(group);
        classRepository.save(c);
    }

    private void submitButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_groupButton1ActionPerformed
        //POP UP SECOND SUBMISSON PAGE WITH GITHUB LINK FIELD
        Assignment assignment = classRepository.findByClassId(319).getProject().getAssignmentList().get(2);
        String context = jTextField1.getText();
        Class c = classRepository.findByClassId(319);
        Submission submission = new Submission(assignment,context);
        c.getProject().getAssignmentList().get(2).addSubmission(submission);
        Group group = groupRepository.findByGroupId(currentUser.getGroupId());
        currentUser.addSubmission(submission,assignment,group);
        Student s = studentRepository.findByUserId(currentUser.getUserId());
        studentRepository.save(s);
        groupRepository.save(group);
        classRepository.save(c);
    }

    private void submitButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_groupButton1ActionPerformed
        //POP UP THIRD SUBMISSON PAGE WITH GITHUB LINK FIELD
        Assignment assignment = classRepository.findByClassId(319).getProject().getAssignmentList().get(3);
        String context = jTextField1.getText();
        Class c = classRepository.findByClassId(319);
        Submission submission = new Submission(assignment,context);
        c.getProject().getAssignmentList().get(3).addSubmission(submission);
        Group group = groupRepository.findByGroupId(currentUser.getGroupId());
        currentUser.addSubmission(submission,assignment,group);
        Student s = studentRepository.findByUserId(currentUser.getUserId());
        studentRepository.save(s);
        groupRepository.save(group);
        classRepository.save(c);
    }

    private void submitButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_groupButton1ActionPerformed
        //POP UP FORTH SUBMISSON PAGE WITH GITHUB LINK FIELD
        Assignment assignment = classRepository.findByClassId(319).getProject().getAssignmentList().get(4);
        String context = jTextField1.getText();
        Class c = classRepository.findByClassId(319);
        Submission submission = new Submission(assignment,context);
        c.getProject().getAssignmentList().get(4).addSubmission(submission);
        Group group = groupRepository.findByGroupId(currentUser.getGroupId());
        currentUser.addSubmission(submission,assignment,group);
        Student s = studentRepository.findByUserId(currentUser.getUserId());
        studentRepository.save(s);
        groupRepository.save(group);
        classRepository.save(c);
    }

    //Peer Review for Group Member 1
    private void groupMemberButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_groupButton1ActionPerformed
        // TODO add your handling code here:
        Group g = groupRepository.findByGroupId(currentUser.getGroupId());
        int id = g.getStudentIdList().get(0);
        Student s = studentRepository.findByUserId(id);
        if(s.getUserId() != currentUser.getUserId()){
            peer = s.getUserId();
            goTo = "PeerReview";
        }
        else{
            UIManager um=new UIManager();
            um.put("OptionPane.background",new Color(120, 88, 161));
            um.put("Panel.background",new Color(120, 88, 161));
            JOptionPane.showMessageDialog(null,"You can't peer review yourself","Set Color",
                    JOptionPane.INFORMATION_MESSAGE);
        }
    }

    private void groupMemberButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_groupButton1ActionPerformed
        // TODO add your handling code here:
        Group g = groupRepository.findByGroupId(currentUser.getGroupId());
        int id = g.getStudentIdList().get(1);
        Student s = studentRepository.findByUserId(id);
        if(s.getUserId() != currentUser.getUserId()){
            peer = s.getUserId();
            goTo = "PeerReview";
        }
        else{
            UIManager um=new UIManager();
            um.put("OptionPane.background",new Color(120, 88, 161));
            um.put("Panel.background",new Color(120, 88, 161));
            JOptionPane.showMessageDialog(null,"You can't peer review yourself","Set Color",
                    JOptionPane.INFORMATION_MESSAGE);
        }
    }

    private void groupMemberButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_groupButton1ActionPerformed
        // TODO add your handling code here:
        Group g = groupRepository.findByGroupId(currentUser.getGroupId());
        int id = g.getStudentIdList().get(2);
        Student s = studentRepository.findByUserId(id);
        if(s.getUserId() != currentUser.getUserId()){
            peer = s.getUserId();
            goTo = "PeerReview";
        }
        else{
            UIManager um=new UIManager();
            um.put("OptionPane.background",new Color(120, 88, 161));
            um.put("Panel.background",new Color(120, 88, 161));
            JOptionPane.showMessageDialog(null,"You can't peer review yourself","Set Color",
                    JOptionPane.INFORMATION_MESSAGE);
        }
    }

    private void groupMemberButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_groupButton1ActionPerformed
        // TODO add your handling code here:
        Group g = groupRepository.findByGroupId(currentUser.getGroupId());
        int id = g.getStudentIdList().get(3);
        Student s = studentRepository.findByUserId(id);
        if(s.getUserId() != currentUser.getUserId()){
            peer = s.getUserId();
            goTo = "PeerReview";
        }
        else{
            UIManager um=new UIManager();
            um.put("OptionPane.background",new Color(120, 88, 161));
            um.put("Panel.background",new Color(120, 88, 161));
            JOptionPane.showMessageDialog(null,"You can't peer review yourself","Set Color",
                    JOptionPane.INFORMATION_MESSAGE);
        }
    }

    private void groupMemberButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_groupButton1ActionPerformed
        // TODO add your handling code here:
        Group g = groupRepository.findByGroupId(currentUser.getGroupId());
        int id = g.getStudentIdList().get(4);
        if(id != currentUser.getUserId()){
            peer = id;
            goTo = "PeerReview";
        }
        else{
            UIManager um=new UIManager();
            um.put("OptionPane.background",new Color(120, 88, 161));
            um.put("Panel.background",new Color(120, 88, 161));
            JOptionPane.showMessageDialog(null,"You can't peer review yourself","Set Color",
                    JOptionPane.INFORMATION_MESSAGE);
        }
    }





    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel announcementsPanel;
    private javax.swing.JPanel calendarPanel;
    private javax.swing.JPanel deadlinesPanel;
    private javax.swing.JButton groupButton1;
    private javax.swing.JButton groupButton10;
    private javax.swing.JButton groupButton11;
    private javax.swing.JButton groupButton2;
    private javax.swing.JButton groupButton3;
    private javax.swing.JButton groupButton4;
    private javax.swing.JButton groupButton5;
    private javax.swing.JButton groupButton6;
    private javax.swing.JButton groupButton7;
    private javax.swing.JButton groupButton8;
    private javax.swing.JButton groupButton9;
    private javax.swing.JButton groupMemberButton1;
    private javax.swing.JButton groupMemberButton2;
    private javax.swing.JButton groupMemberButton3;
    private javax.swing.JButton groupMemberButton4;
    private javax.swing.JButton groupMemberButton5;
    private javax.swing.JLabel groupMemberLabel1;
    private javax.swing.JLabel groupMemberLabel2;
    private javax.swing.JLabel groupMemberLabel3;
    private javax.swing.JLabel groupMemberLabel4;
    private javax.swing.JLabel groupMemberLabel5;
    private javax.swing.JPanel groupMemberPanel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel launchDatePanel;
    private javax.swing.JLabel otherGroupsLabel1;
    private javax.swing.JLabel otherGroupsLabel10;
    private javax.swing.JLabel otherGroupsLabel11;
    private javax.swing.JLabel otherGroupsLabel2;
    private javax.swing.JLabel otherGroupsLabel3;
    private javax.swing.JLabel otherGroupsLabel4;
    private javax.swing.JLabel otherGroupsLabel5;
    private javax.swing.JLabel otherGroupsLabel6;
    private javax.swing.JLabel otherGroupsLabel7;
    private javax.swing.JLabel otherGroupsLabel8;
    private javax.swing.JLabel otherGroupsLabel9;
    private javax.swing.JPanel otherGroupsPanel;
    private javax.swing.JPanel overallProgressPanel;
    private javax.swing.JPanel projectSummaryPanel;
    private javax.swing.JPanel statisticsPanel;
    private javax.swing.JButton submitButton1;
    private javax.swing.JButton submitButton2;
    private javax.swing.JButton submitButton3;
    private javax.swing.JButton submitButton4;
    private javax.swing.JButton submitButton5;
    private javax.swing.JButton submitButton6;
    private javax.swing.JLabel upcomingDeadlinesLabel1;
    private javax.swing.JLabel upcomingDeadlinesLabel2;
    private javax.swing.JLabel upcomingDeadlinesLabel3;
    private javax.swing.JLabel upcomingDeadlinesLabel4;
    private javax.swing.JLabel upcomingDeadlinesLabel5;
    private javax.swing.JLabel upcomingDeadlinesLabel6;
    private javax.swing.JButton viewARButton1;
    private javax.swing.JButton viewARButton2;
    private javax.swing.JButton viewARButton3;
    private javax.swing.JButton viewARButton4;
    private javax.swing.JButton viewARButton5;
    private javax.swing.JButton viewFeedbackButton1;
    private javax.swing.JButton viewFeedbackButton2;
    private javax.swing.JButton viewFeedbackButton3;
    private javax.swing.JButton viewFeedbackButton4;
    private javax.swing.JButton viewFeedbackButton5;
    private javax.swing.JLabel viewReviewLabel1;
    private javax.swing.JLabel viewReviewLabel2;
    private javax.swing.JLabel viewReviewLabel3;
    private javax.swing.JLabel viewReviewLabel4;
    private javax.swing.JLabel viewReviewLabel5;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;

    private javax.swing.JButton acceptButton1;
    private javax.swing.JLabel requestLabel1;

    private javax.swing.JButton acceptButton2;
    private javax.swing.JButton acceptButton3;
    private javax.swing.JButton acceptButton4;
    private javax.swing.JTextArea artifactReviewArea;
    private javax.swing.JLabel artifactReviewLabel;
    private javax.swing.JLabel artifactReviewMainLabel;
    private javax.swing.JLabel artifactReviewURLLabel;
    private javax.swing.JTextField artifactURLField;
    private javax.swing.JCheckBox firstArtifactCheckBox;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton randomArtifactButton;
    private javax.swing.JButton rejectButton1;
    private javax.swing.JButton rejectButton2;
    private javax.swing.JButton rejectButton3;
    private javax.swing.JButton rejectButton4;
    private javax.swing.JLabel requestLabel2;
    private javax.swing.JLabel requestLabel3;
    private javax.swing.JLabel requestLabel4;
    private javax.swing.JCheckBox secondArtifactCheckBox;
    private javax.swing.JButton submitArtifactButton;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
