package cs319.group1e.procheck319;
import java.util.*;

/**
 *
 * @author bedir
 */
public class InstructorGUI extends javax.swing.JFrame {

    private InstructorAndTAs currentUser;
    private InstructorAndTAsRepository instructorAndTAsRepository;
    private GroupRepository groupRepository;
    private ClassRepository classRepository;
    private StudentRepository studentRepository;
    /**
     * Creates new form InstructorGUI
     */
    public InstructorGUI(StudentRepository studentRepository, InstructorAndTAsRepository instructorAndTAsRepository, GroupRepository groupRepository, ClassRepository classRepository) {
        this.instructorAndTAsRepository = instructorAndTAsRepository;
        this.groupRepository = groupRepository;
        this.classRepository = classRepository;
        this.studentRepository = studentRepository;
        initComponents();
    }
    public InstructorAndTAs getCurrentUser() {
        return currentUser;
    }

    public void setCurrentUser(InstructorAndTAs currentUser) {
        this.currentUser = currentUser;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        overallProgressPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        formNewGroupPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        projectSummaryPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        headerPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        launchDatePanel = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        otherGroupsPanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        calendarPanel = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jButton49 = new javax.swing.JButton();
        jButton50 = new javax.swing.JButton();
        jButton54 = new javax.swing.JButton();
        jButton55 = new javax.swing.JButton();
        jButton56 = new javax.swing.JButton();
        invitationsPanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        announcementsPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();
        jButton41 = new javax.swing.JButton();
        jButton42 = new javax.swing.JButton();
        jButton43 = new javax.swing.JButton();
        jButton45 = new javax.swing.JButton();
        jButton46 = new javax.swing.JButton();
        jButton47 = new javax.swing.JButton();
        jButton48 = new javax.swing.JButton();
        jButton51 = new javax.swing.JButton();
        jButton52 = new javax.swing.JButton();
        deadlinesPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();

        overallProgressPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        projectSummaryPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        headerPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        launchDatePanel = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        otherGroupsPanel = new javax.swing.JPanel();
        artifactReviewMainLabel = new javax.swing.JLabel();
        addAssignmentToClass = new javax.swing.JButton();
        assignmentStartLabel = new javax.swing.JLabel();
        createAssignmentButton = new javax.swing.JButton();
        assignmentStartMonthField = new javax.swing.JTextField();
        assignmentStartYearField = new javax.swing.JTextField();
        assignmentEndLabel = new javax.swing.JLabel();
        assignmentStartDayField = new javax.swing.JTextField();
        assignmentEndDayField = new javax.swing.JTextField();
        assignmentEndMonthField = new javax.swing.JTextField();
        assignmentEndYearField = new javax.swing.JTextField();
        artifactDeadlineMonthField = new javax.swing.JTextField();
        artifactDeadlineDayField = new javax.swing.JTextField();
        artifactDeadlineLabel = new javax.swing.JLabel();
        artifactDeadlineYearField = new javax.swing.JTextField();
        assignmentTitleLabel = new javax.swing.JLabel();
        assignmentTitleField = new javax.swing.JTextField();
        assignmentWeightLabel = new javax.swing.JLabel();
        assignmentWeightField = new javax.swing.JTextField();
        calendarPanel = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        announcementsPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        deadlinesPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1920, 1000));

        overallProgressPanel.setBackground(new java.awt.Color(232, 235, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Overall Progress");
//------------
        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);


        double progress = 0;
        double counter = 0;

        Project p = classRepository.findByClassId(319).getProject();

        for(int i = 0 ; i < p.getAssignmentList().size() ; i++ ){
            if( p.getAssignmentList().get(i).isDeadlineOver() ){
                counter ++;
            }
        }

        progress = (counter/p.getAssignmentList().size())*100;


        jLabel4.setText(Double.toString(progress));
//--------------
        javax.swing.GroupLayout overallProgressPanelLayout = new javax.swing.GroupLayout(overallProgressPanel);
        overallProgressPanel.setLayout(overallProgressPanelLayout);
        overallProgressPanelLayout.setHorizontalGroup(
                overallProgressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(overallProgressPanelLayout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        overallProgressPanelLayout.setVerticalGroup(
                overallProgressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(overallProgressPanelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        formNewGroupPanel.setBackground(new java.awt.Color(232, 235, 255));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Manage Project");

        jButton1.setText("Generate Random Groups");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateRandomGroupsActionPerformed(evt);
            }
        });

        jButton2.setText("Add Announcement");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAnnouncementActionPerformed(evt);
            }
        });

        jButton3.setText("Announce To A Group");


        javax.swing.GroupLayout formNewGroupPanelLayout = new javax.swing.GroupLayout(formNewGroupPanel);
        formNewGroupPanel.setLayout(formNewGroupPanelLayout);
        formNewGroupPanelLayout.setHorizontalGroup(
                formNewGroupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(formNewGroupPanelLayout.createSequentialGroup()
                                .addGroup(formNewGroupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(formNewGroupPanelLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(formNewGroupPanelLayout.createSequentialGroup()
                                                .addGap(22, 22, 22)
                                                .addGroup(formNewGroupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
        );
        formNewGroupPanelLayout.setVerticalGroup(
                formNewGroupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(formNewGroupPanelLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel3)
                                .addGap(46, 46, 46)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        projectSummaryPanel.setBackground(new java.awt.Color(232, 235, 255));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Project Summary");

        jLabel59.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel59.setText("Start Date : ");

        jLabel60.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel60.setText("End Date :");

        jLabel61.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel61.setText("Project Leader :");

        jLabel62.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel62.setText("05.01.2022");

        jLabel63.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel63.setText("Eray Tüzün");

        jLabel64.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel64.setText("01.10.2021");

        javax.swing.GroupLayout projectSummaryPanelLayout = new javax.swing.GroupLayout(projectSummaryPanel);
        projectSummaryPanel.setLayout(projectSummaryPanelLayout);
        projectSummaryPanelLayout.setHorizontalGroup(
                projectSummaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(projectSummaryPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(projectSummaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(projectSummaryPanelLayout.createSequentialGroup()
                                                .addGroup(projectSummaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel59)
                                                        .addComponent(jLabel60)
                                                        .addComponent(jLabel61))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
                        .addGroup(projectSummaryPanelLayout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addGroup(projectSummaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel64)
                                        .addComponent(jLabel63)
                                        .addComponent(jLabel62))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        projectSummaryPanelLayout.setVerticalGroup(
                projectSummaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(projectSummaryPanelLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel5)
                                .addGap(85, 85, 85)
                                .addComponent(jLabel59)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel64)
                                .addGap(44, 44, 44)
                                .addComponent(jLabel60)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel62)
                                .addGap(50, 50, 50)
                                .addComponent(jLabel61)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel63)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        headerPanel.setBackground(new java.awt.Color(232, 235, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CS 319");

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
                headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(headerPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 1282, Short.MAX_VALUE)
                                .addContainerGap())
        );
        headerPanelLayout.setVerticalGroup(
                headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(headerPanelLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(26, Short.MAX_VALUE))
        );

        launchDatePanel.setBackground(new java.awt.Color(232, 235, 255));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Projected Launch Date");

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel22.setText(classRepository.findByClassId(319).getProject().getDeadline());

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel23.setText("56 Days Remaining");

        javax.swing.GroupLayout launchDatePanelLayout = new javax.swing.GroupLayout(launchDatePanel);
        launchDatePanel.setLayout(launchDatePanelLayout);
        launchDatePanelLayout.setHorizontalGroup(
                launchDatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(launchDatePanelLayout.createSequentialGroup()
                                .addGroup(launchDatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(launchDatePanelLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE))
                                        .addGroup(launchDatePanelLayout.createSequentialGroup()
                                                .addGroup(launchDatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(launchDatePanelLayout.createSequentialGroup()
                                                                .addGap(116, 116, 116)
                                                                .addComponent(jLabel22))
                                                        .addGroup(launchDatePanelLayout.createSequentialGroup()
                                                                .addGap(104, 104, 104)
                                                                .addComponent(jLabel23)))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
        );
        launchDatePanelLayout.setVerticalGroup(
                launchDatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(launchDatePanelLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel22)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel23)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        //Assignment Panel
        otherGroupsPanel.setBackground(new java.awt.Color(232, 235, 255));

        artifactReviewMainLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        artifactReviewMainLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        artifactReviewMainLabel.setText("Assignment");

        addAssignmentToClass.setBackground(new java.awt.Color(120, 88, 161));
        addAssignmentToClass.setForeground(new java.awt.Color(255, 255, 255));
        addAssignmentToClass.setText("Create New Assignment");
        addAssignmentToClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                //addAssignmentToClassActionPerformed(evt);
            }
        });

        assignmentStartLabel.setText("Start Date");

        createAssignmentButton.setBackground(new java.awt.Color(120, 88, 161));
        createAssignmentButton.setForeground(new java.awt.Color(255, 255, 255));
        createAssignmentButton.setText("Create Assignment");
        createAssignmentButton.setEnabled(false);

        assignmentStartMonthField.setText("Month");
        assignmentStartMonthField.setEnabled(false);

        assignmentStartYearField.setText("Year");
        assignmentStartYearField.setEnabled(false);

        assignmentEndLabel.setText("End Date");

        assignmentStartDayField.setEditable(false);
        assignmentStartDayField.setText("Day");
        assignmentStartDayField.setEnabled(false);
        assignmentStartDayField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                //assignmentStartDayFieldActionPerformed(evt);
            }
        });

        assignmentEndDayField.setText("Day");
        assignmentEndDayField.setEnabled(false);

        assignmentEndMonthField.setText("Month");
        assignmentEndMonthField.setEnabled(false);

        assignmentEndYearField.setText("Year");
        assignmentEndYearField.setEnabled(false);
        assignmentEndYearField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                //assignmentEndYearFieldActionPerformed(evt);
            }
        });

        artifactDeadlineMonthField.setText("Month");
        artifactDeadlineMonthField.setEnabled(false);

        artifactDeadlineDayField.setText("Day");
        artifactDeadlineDayField.setEnabled(false);
        artifactDeadlineDayField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                //artifactDeadlineDayFieldActionPerformed(evt);
            }
        });

        artifactDeadlineLabel.setText("Artifact Review Deadline");

        artifactDeadlineYearField.setText("Year");
        artifactDeadlineYearField.setEnabled(false);

        assignmentTitleLabel.setText("Assignment Title");

        assignmentTitleField.setEnabled(false);

        assignmentWeightLabel.setText("Assignment Weight");

        assignmentWeightField.setEnabled(false);
        assignmentWeightField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                //assignmentWeightFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout otherGroupsPanelLayout = new javax.swing.GroupLayout(otherGroupsPanel);
        otherGroupsPanel.setLayout(otherGroupsPanelLayout);
        otherGroupsPanelLayout.setHorizontalGroup(
                otherGroupsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(otherGroupsPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(otherGroupsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, otherGroupsPanelLayout.createSequentialGroup()
                                                .addGap(0, 45, Short.MAX_VALUE)
                                                .addComponent(addAssignmentToClass, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(45, 45, 45))
                                        .addGroup(otherGroupsPanelLayout.createSequentialGroup()
                                                .addGroup(otherGroupsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(artifactReviewMainLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addGroup(otherGroupsPanelLayout.createSequentialGroup()
                                                                .addGroup(otherGroupsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(otherGroupsPanelLayout.createSequentialGroup()
                                                                                .addGroup(otherGroupsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addGroup(otherGroupsPanelLayout.createSequentialGroup()
                                                                                                .addGroup(otherGroupsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                                                        .addComponent(assignmentEndLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                                        .addComponent(assignmentStartLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))
                                                                                                .addGap(18, 18, 18)
                                                                                                .addGroup(otherGroupsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                                                        .addComponent(assignmentEndDayField)
                                                                                                        .addComponent(assignmentStartDayField, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)))
                                                                                        .addComponent(artifactDeadlineLabel))
                                                                                .addGap(11, 11, 11))
                                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, otherGroupsPanelLayout.createSequentialGroup()
                                                                                .addComponent(artifactDeadlineDayField, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                                                .addGroup(otherGroupsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addGroup(otherGroupsPanelLayout.createSequentialGroup()
                                                                                .addComponent(artifactDeadlineMonthField, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(artifactDeadlineYearField, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addGroup(otherGroupsPanelLayout.createSequentialGroup()
                                                                                .addGroup(otherGroupsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                                        .addComponent(assignmentStartMonthField, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                                                                                        .addComponent(assignmentEndMonthField))
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                .addGroup(otherGroupsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                                        .addComponent(assignmentStartYearField, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                                                                                        .addComponent(assignmentEndYearField))))
                                                                .addGap(0, 0, Short.MAX_VALUE)))
                                                .addContainerGap())
                                        .addGroup(otherGroupsPanelLayout.createSequentialGroup()
                                                .addGroup(otherGroupsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(assignmentWeightLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(assignmentTitleLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(otherGroupsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(assignmentTitleField)
                                                        .addComponent(assignmentWeightField, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE))
                                                .addGap(0, 0, Short.MAX_VALUE))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, otherGroupsPanelLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(createAssignmentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );
        otherGroupsPanelLayout.setVerticalGroup(
                otherGroupsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(otherGroupsPanelLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(artifactReviewMainLabel)
                                .addGap(18, 18, 18)
                                .addComponent(addAssignmentToClass, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(otherGroupsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(assignmentStartYearField, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                                        .addComponent(assignmentStartLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(assignmentStartDayField)
                                        .addComponent(assignmentStartMonthField))
                                .addGap(18, 18, 18)
                                .addGroup(otherGroupsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(assignmentEndLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(assignmentEndYearField)
                                        .addComponent(assignmentEndMonthField)
                                        .addComponent(assignmentEndDayField))
                                .addGap(18, 18, 18)
                                .addComponent(artifactDeadlineLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(otherGroupsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(artifactDeadlineMonthField, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(artifactDeadlineDayField, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(artifactDeadlineYearField, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(otherGroupsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(assignmentTitleField, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                                        .addComponent(assignmentTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(otherGroupsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(assignmentWeightField, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                                        .addComponent(assignmentWeightLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(294, 294, 294)
                                .addComponent(createAssignmentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );

        //-------------------------ANNOUNCEMENT PART-------------------------
        calendarPanel.setBackground(new java.awt.Color(232, 235, 255));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Announcements");

        jLabel54.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel54.setText("Announcement 1");

        jLabel55.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel55.setText("Announcement 2");

        jLabel56.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel56.setText("Announcement 3");

        jLabel57.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel57.setText("Announcement 4");

        jLabel58.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel58.setText("Announcement 5");

        jButton49.setText("View Announcement");
        jButton49.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton49ActionPerformed(evt);
            }
        });

        jButton50.setText("View Announcement");

        jButton54.setText("View Announcement");

        jButton55.setText("View Announcement");

        jButton56.setText("View Announcement");

        javax.swing.GroupLayout calendarPanelLayout = new javax.swing.GroupLayout(calendarPanel);
        calendarPanel.setLayout(calendarPanelLayout);
        calendarPanelLayout.setHorizontalGroup(
                calendarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(calendarPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                        .addGroup(calendarPanelLayout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addGroup(calendarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel54)
                                        .addComponent(jLabel55)
                                        .addComponent(jLabel56)
                                        .addComponent(jLabel57)
                                        .addComponent(jLabel58))
                                .addGap(58, 58, 58)
                                .addGroup(calendarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButton56)
                                        .addComponent(jButton55)
                                        .addComponent(jButton54)
                                        .addComponent(jButton49)
                                        .addComponent(jButton50))
                                .addContainerGap(397, Short.MAX_VALUE))
        );
        calendarPanelLayout.setVerticalGroup(
                calendarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(calendarPanelLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(calendarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(calendarPanelLayout.createSequentialGroup()
                                                .addComponent(jLabel24)
                                                .addGap(45, 45, 45)
                                                .addComponent(jLabel54))
                                        .addComponent(jButton49))
                                .addGap(16, 16, 16)
                                .addGroup(calendarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel55)
                                        .addComponent(jButton50))
                                .addGap(18, 18, 18)
                                .addGroup(calendarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel56)
                                        .addComponent(jButton54))
                                .addGap(18, 18, 18)
                                .addGroup(calendarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel57)
                                        .addComponent(jButton55))
                                .addGap(13, 13, 13)
                                .addGroup(calendarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel58)
                                        .addComponent(jButton56))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        invitationsPanel.setBackground(new java.awt.Color(232, 235, 255));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Average Grades");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Assignment 1 :");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Assignment 2 :");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Assignment 3 :");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Assignment 4 :");

        Class aClass = classRepository.findByClassId(319);
        boolean flag = true;

        if( p.getAssignmentList()!=null ){

            aClass.calculateAllAverages();
            for( int i = 0 ; i < aClass.getAverages().size() ; i++ ) {

                flag = false;

                if(aClass.getAverages().get(i) == 0){

                    jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                    jLabel17.setText("No");

                    jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                    jLabel18.setText("No");

                    jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                    jLabel19.setText("No");

                    jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                    jLabel20.setText("No");

                    jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                    jLabel21.setText("No");
                }

                else {

                    if (i == 1) {

                        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                        jLabel17.setText(Double.toString(aClass.getAverages().get(0)));

                        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                        jLabel18.setText("No");

                        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                        jLabel19.setText("No");

                        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                        jLabel20.setText("No");

                        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                        jLabel21.setText("No");
                    }
                    if (i == 2) {

                        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                        jLabel18.setText(Double.toString(aClass.getAverages().get(1)));
                    }
                    if (i == 3) {

                        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                        jLabel19.setText(Double.toString(aClass.getAverages().get(2)));
                    }
                    if (i == 4) {

                        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                        jLabel20.setText(Double.toString(aClass.getAverages().get(3)));
                    }
                    if (i == 5) {

                        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                        jLabel21.setText(Double.toString(aClass.getAverages().get(4)));
                    }
                }
            }

            if(flag){

                jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                jLabel17.setText("No");

                jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                jLabel18.setText("No");

                jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                jLabel19.setText("No");

                jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                jLabel20.setText("No");

                jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                jLabel21.setText("No");
            }

        }

        else {

            jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
            jLabel17.setText("No");

            jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
            jLabel18.setText("No");

            jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
            jLabel19.setText("No");

            jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
            jLabel20.setText("No");

            jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
            jLabel21.setText("No");
        }

        jButton4.setText("View Submssion List");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Assignment 5 :");

        jButton5.setText("View Submssion List");

        jButton6.setText("View Submssion List");

        jButton7.setText("View Submssion List");

        jButton8.setText("View Submssion List");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout invitationsPanelLayout = new javax.swing.GroupLayout(invitationsPanel);
        invitationsPanel.setLayout(invitationsPanelLayout);
        invitationsPanelLayout.setHorizontalGroup(
                invitationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(invitationsPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(invitationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
                                        .addGroup(invitationsPanelLayout.createSequentialGroup()
                                                .addGap(121, 121, 121)
                                                .addGroup(invitationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(invitationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, invitationsPanelLayout.createSequentialGroup()
                                                                        .addGap(211, 211, 211)
                                                                        .addGroup(invitationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jButton7, javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                .addComponent(jButton8, javax.swing.GroupLayout.Alignment.TRAILING)))
                                                                .addGroup(invitationsPanelLayout.createSequentialGroup()
                                                                        .addGroup(invitationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                .addGroup(invitationsPanelLayout.createSequentialGroup()
                                                                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                        .addGap(18, 18, 18)
                                                                                        .addComponent(jLabel18))
                                                                                .addGroup(invitationsPanelLayout.createSequentialGroup()
                                                                                        .addComponent(jLabel15)
                                                                                        .addGap(18, 18, 18)
                                                                                        .addComponent(jLabel17))
                                                                                .addGroup(invitationsPanelLayout.createSequentialGroup()
                                                                                        .addComponent(jLabel13)
                                                                                        .addGap(18, 18, 18)
                                                                                        .addComponent(jLabel19))
                                                                                .addGroup(invitationsPanelLayout.createSequentialGroup()
                                                                                        .addComponent(jLabel14)
                                                                                        .addGap(18, 18, 18)
                                                                                        .addComponent(jLabel20))
                                                                                .addGroup(invitationsPanelLayout.createSequentialGroup()
                                                                                        .addComponent(jLabel16)
                                                                                        .addGap(18, 18, 18)
                                                                                        .addComponent(jLabel21)))
                                                                        .addGap(86, 86, 86)
                                                                        .addGroup(invitationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                                .addComponent(jButton4)
                                                                                .addComponent(jButton5))))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, invitationsPanelLayout.createSequentialGroup()
                                                                .addGap(16, 16, 16)
                                                                .addComponent(jButton6)))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
        );
        invitationsPanelLayout.setVerticalGroup(
                invitationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(invitationsPanelLayout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jLabel9)
                                .addGap(32, 32, 32)
                                .addGroup(invitationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(invitationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel15)
                                                .addComponent(jLabel17))
                                        .addComponent(jButton4))
                                .addGap(15, 15, 15)
                                .addGroup(invitationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel18)
                                        .addComponent(jButton5)
                                        .addComponent(jLabel12))
                                .addGap(18, 18, 18)
                                .addGroup(invitationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel13)
                                        .addComponent(jButton6)
                                        .addComponent(jLabel19))
                                .addGap(18, 18, 18)
                                .addGroup(invitationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel14)
                                        .addComponent(jLabel20)
                                        .addComponent(jButton7))
                                .addGap(18, 18, 18)
                                .addGroup(invitationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel16)
                                        .addComponent(jLabel21)
                                        .addComponent(jButton8))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        announcementsPanel.setBackground(new java.awt.Color(232, 235, 255));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Submissions");

        jLabel46.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel46.setText("Group 5's Submission For Assignment 4");

        jLabel47.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel47.setText("Group 5's Submission For Assignment 4");

        jLabel48.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel48.setText("Group 5's Submission For Assignment 4");

        jLabel49.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel49.setText("Group 5's Submission For Assignment 4");

        jLabel50.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel50.setText("Group 5's Submission For Assignment 4");

        jLabel51.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel51.setText("Group 5's Submission For Assignment 4");

        jLabel52.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel52.setText("Group 5's Submission For Assignment 4");

        jButton20.setText("Give Feedback");

        jButton21.setText("Grade");

        jButton22.setText("View Artifact Reviews");

        jButton23.setText("View");

        jButton24.setText("View");

        jButton25.setText("View");

        jButton26.setText("View");

        jButton27.setText("View");

        jButton28.setText("View");

        jButton29.setText("View");

        jButton31.setText("Give Feedback");

        jButton32.setText("Give Feedback");

        jButton33.setText("Give Feedback");

        jButton34.setText("Give Feedback");

        jButton35.setText("Give Feedback");

        jButton36.setText("Give Feedback");

        jButton38.setText("Grade");

        jButton39.setText("Grade");

        jButton40.setText("Grade");

        jButton41.setText("Grade");

        jButton42.setText("Grade");

        jButton43.setText("Grade");

        jButton45.setText("View Artifact Reviews");

        jButton46.setText("View Artifact Reviews");

        jButton47.setText("View Artifact Reviews");

        jButton48.setText("View Artifact Reviews");

        jButton51.setText("View Artifact Reviews");

        jButton52.setText("View Artifact Reviews");

        javax.swing.GroupLayout announcementsPanelLayout = new javax.swing.GroupLayout(announcementsPanel);
        announcementsPanel.setLayout(announcementsPanelLayout);
        announcementsPanelLayout.setHorizontalGroup(
                announcementsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(announcementsPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(announcementsPanelLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(announcementsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel46)
                                        .addComponent(jLabel52)
                                        .addComponent(jLabel51)
                                        .addComponent(jLabel50)
                                        .addComponent(jLabel49)
                                        .addComponent(jLabel48)
                                        .addComponent(jLabel47))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(announcementsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(announcementsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(announcementsPanelLayout.createSequentialGroup()
                                                        .addComponent(jButton23)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(jButton20)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jButton21)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jButton22))
                                                .addGroup(announcementsPanelLayout.createSequentialGroup()
                                                        .addComponent(jButton24)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(jButton31)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jButton38)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jButton45))
                                                .addGroup(announcementsPanelLayout.createSequentialGroup()
                                                        .addComponent(jButton26)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(jButton33)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jButton40)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jButton47))
                                                .addGroup(announcementsPanelLayout.createSequentialGroup()
                                                        .addComponent(jButton27)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(jButton34)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jButton41)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jButton48))
                                                .addGroup(announcementsPanelLayout.createSequentialGroup()
                                                        .addComponent(jButton28)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(jButton35)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jButton42)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jButton51))
                                                .addGroup(announcementsPanelLayout.createSequentialGroup()
                                                        .addComponent(jButton29)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(jButton36)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jButton43)
                                                        .addPreferredGap(
                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jButton52)))
                                        .addGroup(announcementsPanelLayout.createSequentialGroup()
                                                .addComponent(jButton25)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jButton32)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButton39)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jButton46)))
                                .addContainerGap())
        );
        announcementsPanelLayout.setVerticalGroup(
                announcementsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(announcementsPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel6)
                                .addGap(57, 57, 57)
                                .addGroup(announcementsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel46)
                                        .addComponent(jButton20)
                                        .addComponent(jButton21)
                                        .addComponent(jButton22)
                                        .addComponent(jButton23))
                                .addGap(29, 29, 29)
                                .addGroup(announcementsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel47)
                                        .addComponent(jButton24)
                                        .addComponent(jButton31)
                                        .addComponent(jButton38)
                                        .addComponent(jButton45))
                                .addGap(27, 27, 27)
                                .addGroup(announcementsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel48)
                                        .addComponent(jButton25)
                                        .addComponent(jButton32)
                                        .addComponent(jButton39)
                                        .addComponent(jButton46))
                                .addGap(25, 25, 25)
                                .addGroup(announcementsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel49)
                                        .addComponent(jButton26)
                                        .addComponent(jButton33)
                                        .addComponent(jButton40)
                                        .addComponent(jButton47))
                                .addGap(29, 29, 29)
                                .addGroup(announcementsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel50)
                                        .addComponent(jButton27)
                                        .addComponent(jButton34)
                                        .addComponent(jButton41)
                                        .addComponent(jButton48))
                                .addGap(31, 31, 31)
                                .addGroup(announcementsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel51)
                                        .addComponent(jButton28)
                                        .addComponent(jButton35)
                                        .addComponent(jButton42)
                                        .addComponent(jButton51))
                                .addGap(35, 35, 35)
                                .addGroup(announcementsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel52)
                                        .addComponent(jButton29)
                                        .addComponent(jButton36)
                                        .addComponent(jButton43)
                                        .addComponent(jButton52))
                                .addContainerGap(86, Short.MAX_VALUE))
        );

        deadlinesPanel.setBackground(new java.awt.Color(232, 235, 255));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Current Assignments");

        jLabel36.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel36.setText("Assignment 1");

        jLabel37.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel37.setText("Assignment 2");

        jLabel38.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel38.setText("Assignment 3");

        jLabel39.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel39.setText("Assignment 4");

        jLabel40.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel40.setText("Assignment 5");

        jLabel41.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel41.setText("Deadline: 12/04/2020");

        jLabel42.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel42.setText("Deadline: 13/04/2020");

        jLabel43.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel43.setText("Deadline: 14/04/2020");

        jLabel44.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel44.setText("Deadline: 15/04/2020");

        jLabel45.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel45.setText("Deadline: 16/04/2020");

        javax.swing.GroupLayout deadlinesPanelLayout = new javax.swing.GroupLayout(deadlinesPanel);
        deadlinesPanel.setLayout(deadlinesPanelLayout);
        deadlinesPanelLayout.setHorizontalGroup(
                deadlinesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(deadlinesPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(deadlinesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE))
                                .addContainerGap())
                        .addGroup(deadlinesPanelLayout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addGroup(deadlinesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel36)
                                        .addComponent(jLabel37)
                                        .addComponent(jLabel38)
                                        .addComponent(jLabel39)
                                        .addComponent(jLabel40))
                                .addGap(78, 78, 78)
                                .addGroup(deadlinesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel45)
                                        .addComponent(jLabel44)
                                        .addComponent(jLabel43)
                                        .addComponent(jLabel42)
                                        .addComponent(jLabel41))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        deadlinesPanelLayout.setVerticalGroup(
                deadlinesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(deadlinesPanelLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11)
                                .addGap(64, 64, 64)
                                .addGroup(deadlinesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel36)
                                        .addComponent(jLabel41))
                                .addGap(42, 42, 42)
                                .addGroup(deadlinesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel37)
                                        .addComponent(jLabel42))
                                .addGap(40, 40, 40)
                                .addGroup(deadlinesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel38)
                                        .addComponent(jLabel43))
                                .addGap(50, 50, 50)
                                .addGroup(deadlinesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel39)
                                        .addComponent(jLabel44))
                                .addGap(44, 44, 44)
                                .addGroup(deadlinesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel40)
                                        .addComponent(jLabel45))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(overallProgressPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(18, 18, 18)
                                                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(projectSummaryPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(formNewGroupPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                .addComponent(calendarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(26, 26, 26)
                                                                .addComponent(invitationsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                .addComponent(announcementsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(deadlinesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(otherGroupsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(launchDatePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(launchDatePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(overallProgressPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(otherGroupsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(calendarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(formNewGroupPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(invitationsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(deadlinesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(announcementsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(projectSummaryPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>

    private void generateRandomGroupsActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        List<Group> groups = new ArrayList<>();
        if(groupRepository != null) {
            groups = groupRepository.findAll();
        }
        List<Student> students = studentRepository.findAll();
        HashMap<Integer, List<Student>> studentsGroupsMap = new HashMap<>();
        Class c = classRepository.findByClassId(319);
        //iterate over groups
        for (int i = 0; i < groups.size(); i++) {
            //create an empty student list to put group students and put that into map
            List<Student> g = new ArrayList<>();
            //iterate over students
            for (int j = 0; j < students.size(); j++) {
                if (students.get(j).getGroupId() == groups.get(i).getGroupId()) {
                    g.add(students.get(j));
                }
            }
            studentsGroupsMap.put(groups.get(i).getGroupId(), g);
        }
        c.formRandomGroups(groups, studentsGroupsMap, students,c);
        groupRepository.saveAll(groups);
        studentRepository.saveAll(students);
        classRepository.save(c);

    }

    private void addAnnouncementActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        //POP UP OLARAK TEXT FIELD SAYFASI GELMESİ GEREKİYOR
    }

    private void viewGroup1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:

    }

    private void viewGroup2ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:

    }

    private void viewGroup3ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:

    }

    private void viewGroup4ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:

    }

    private void viewGroup5ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:

    }

    private void viewGroup6ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:

    }

    private void viewGroup7ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:

    }

    private void viewGroup8ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:

    }

    private void viewGroup9ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:

    }

    private void viewGroup10ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:

    }

    private void viewGroup11ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:

    }

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jButton49ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        // will show the submissions of the assignment

        //get class
        //get assignment list
        //get submission list of each assignment
        //display submission

    }

    // Variables declaration - do not modify
    private javax.swing.JPanel announcementsPanel;
    private javax.swing.JPanel calendarPanel;
    private javax.swing.JPanel deadlinesPanel;
    private javax.swing.JPanel formNewGroupPanel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JPanel invitationsPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton42;
    private javax.swing.JButton jButton43;
    private javax.swing.JButton jButton45;
    private javax.swing.JButton jButton46;
    private javax.swing.JButton jButton47;
    private javax.swing.JButton jButton48;
    private javax.swing.JButton jButton49;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton50;
    private javax.swing.JButton jButton51;
    private javax.swing.JButton jButton52;
    private javax.swing.JButton jButton54;
    private javax.swing.JButton jButton55;
    private javax.swing.JButton jButton56;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JPanel launchDatePanel;
    private javax.swing.JPanel otherGroupsPanel;
    private javax.swing.JPanel overallProgressPanel;
    private javax.swing.JPanel projectSummaryPanel;
    private javax.swing.JButton addAssignmentToClass;
    private javax.swing.JTextField artifactDeadlineDayField;
    private javax.swing.JLabel artifactDeadlineLabel;
    private javax.swing.JTextField artifactDeadlineMonthField;
    private javax.swing.JTextField artifactDeadlineYearField;
    private javax.swing.JLabel artifactReviewMainLabel;
    private javax.swing.JTextField assignmentEndDayField;
    private javax.swing.JLabel assignmentEndLabel;
    private javax.swing.JTextField assignmentEndMonthField;
    private javax.swing.JTextField assignmentEndYearField;
    private javax.swing.JTextField assignmentStartDayField;
    private javax.swing.JLabel assignmentStartLabel;
    private javax.swing.JTextField assignmentStartMonthField;
    private javax.swing.JTextField assignmentStartYearField;
    private javax.swing.JTextField assignmentTitleField;
    private javax.swing.JLabel assignmentTitleLabel;
    private javax.swing.JTextField assignmentWeightField;
    private javax.swing.JLabel assignmentWeightLabel;
    private javax.swing.JButton createAssignmentButton;
    // End of variables declaration
}

