package cs319.group1e.procheck319;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Utku
 */
public class ReviewArtifact extends javax.swing.JFrame {

    private Student currentUser;
    private InstructorAndTAsRepository instructorAndTAsRepository;
    private StudentRepository studentRepository;
    private GroupRepository groupRepository;
    private ClassRepository classRepository;
    private int artifactReviewGroupId;

    /**
     * Creates new form ReviewArtifact
     */
    public ReviewArtifact(InstructorAndTAsRepository instructorAndTAsRepository, StudentRepository studentRepository, GroupRepository groupRepository, ClassRepository classRepository) {
        this.studentRepository = studentRepository;
        this.instructorAndTAsRepository = instructorAndTAsRepository;
        this.groupRepository = groupRepository;
        this.classRepository = classRepository;
        initComponents();
    }

    public void setCurrentUser(Student currentUser) {
        this.currentUser = currentUser;
    }

    public Student getCurrentUser() {
        return this.currentUser;
    }


    public int getArtifactReviewGroupId() {
        return artifactReviewGroupId;
    }
    public void setArtifactReviewGroupId(int artifactReviewGroupId) {
        this.artifactReviewGroupId = artifactReviewGroupId;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        reviewArtifactPanel = new javax.swing.JPanel();
        artifactURLHeaderLabel = new javax.swing.JLabel();
        artifactURLField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        submitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Artifact Review");

        reviewArtifactPanel.setBackground(new java.awt.Color(255, 255, 255));

        artifactURLHeaderLabel.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        artifactURLHeaderLabel.setText("Artifact's Direct Access URL: ");

        artifactURLField.setEditable(false);
        artifactURLField.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        artifactURLField.setText("www.google.com");

        jLabel1.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jLabel1.setText("Artifact Review Feedback");

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        submitButton.setBackground(new java.awt.Color(120, 88, 161));
        submitButton.setForeground(new java.awt.Color(255, 255, 255));
        submitButton.setText("Submit");

        javax.swing.GroupLayout reviewArtifactPanelLayout = new javax.swing.GroupLayout(reviewArtifactPanel);
        reviewArtifactPanel.setLayout(reviewArtifactPanelLayout);
        reviewArtifactPanelLayout.setHorizontalGroup(
                reviewArtifactPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(reviewArtifactPanelLayout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addGroup(reviewArtifactPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(reviewArtifactPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jScrollPane1)
                                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(reviewArtifactPanelLayout.createSequentialGroup()
                                                        .addComponent(artifactURLHeaderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(artifactURLField, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(49, Short.MAX_VALUE))
        );
        reviewArtifactPanelLayout.setVerticalGroup(
                reviewArtifactPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(reviewArtifactPanelLayout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(reviewArtifactPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(artifactURLHeaderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(artifactURLField, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(reviewArtifactPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(reviewArtifactPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>


    // Variables declaration - do not modify
    private javax.swing.JTextField artifactURLField;
    private javax.swing.JLabel artifactURLHeaderLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel reviewArtifactPanel;
    private javax.swing.JButton submitButton;
    // End of variables declaration
}
