package cs319.group1e.procheck319;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import javax.swing.*;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Utku
 */
public class PopUpPeerReview extends javax.swing.JFrame {

    private Student currentUser;
    private InstructorAndTAsRepository instructorAndTAsRepository;
    private StudentRepository studentRepository;
    private GroupRepository groupRepository;
    private ClassRepository classRepository;
    private int newStudentId;

    /**
     * Creates new form PopUpPeerReview
     */
    public PopUpPeerReview(InstructorAndTAsRepository instructorAndTAsRepository, StudentRepository studentRepository, GroupRepository groupRepository, ClassRepository classRepository) {
        this.studentRepository = studentRepository;
        this.instructorAndTAsRepository = instructorAndTAsRepository;
        this.groupRepository = groupRepository;
        this.classRepository = classRepository;
        initComponents();
    }

    public void setCurrentUser(Student currentUser) {
        this.currentUser = currentUser;
    }

    public Student getCurrentUser() {
        return this.currentUser;
    }


    public int getNewStudentId() {
        return newStudentId;
    }
    public void setNewStudentId(int newStudentId) {
        this.newStudentId = newStudentId;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        qOnePOneRB = new javax.swing.JRadioButton();
        qOnePTwoRB = new javax.swing.JRadioButton();
        qOnePThreeRB = new javax.swing.JRadioButton();
        qOnePFourRB = new javax.swing.JRadioButton();
        qOnePFiveRB = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        qTwoPOneRB = new javax.swing.JRadioButton();
        qTwoPTwoRB = new javax.swing.JRadioButton();
        qTwoPThreeRB = new javax.swing.JRadioButton();
        qTwoPFourRB = new javax.swing.JRadioButton();
        qTwoPFiveRB = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        qThreePOneRB = new javax.swing.JRadioButton();
        qThreePTwoRB = new javax.swing.JRadioButton();
        qThreePThreeRB = new javax.swing.JRadioButton();
        qThreePFourRB = new javax.swing.JRadioButton();
        qThreePFiveRB = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        qFourPOneRB = new javax.swing.JRadioButton();
        qFourPTwoRB = new javax.swing.JRadioButton();
        qFourPThreeRB = new javax.swing.JRadioButton();
        qFourPFourRB = new javax.swing.JRadioButton();
        qFourPFiveRB = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        qFivePOneRB = new javax.swing.JRadioButton();
        qFivePTwoRB = new javax.swing.JRadioButton();
        qFivePThreeRB = new javax.swing.JRadioButton();
        qFivePFourRB = new javax.swing.JRadioButton();
        qFivePFiveRB = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        submitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setName("PeerReviewFrame"); // NOI18N
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);

        jLabel1.setBackground(new java.awt.Color(120, 88, 161));
        jLabel1.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jLabel1.setText("Review your peer performance for Analysis Report");

        buttonGroup1.add(qOnePOneRB);
        qOnePOneRB.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        qOnePOneRB.setText("One");
        qOnePOneRB.setToolTipText("");


        buttonGroup1.add(qOnePTwoRB);
        qOnePTwoRB.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        qOnePTwoRB.setText("Two");

        buttonGroup1.add(qOnePThreeRB);
        qOnePThreeRB.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        qOnePThreeRB.setText("Three");

        buttonGroup1.add(qOnePFourRB);
        qOnePFourRB.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        qOnePFourRB.setText("Four");

        buttonGroup1.add(qOnePFiveRB);
        qOnePFiveRB.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        qOnePFiveRB.setText("Five");

        jLabel2.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jLabel2.setText("Review your peer performance for Design Report");

        /*
        buttonGroup1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qOnePOneRBActionPerformed(evt);
            }
        });
        */

        buttonGroup2.add(qTwoPOneRB);
        qTwoPOneRB.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        qTwoPOneRB.setText("One");

        buttonGroup2.add(qTwoPTwoRB);
        qTwoPTwoRB.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        qTwoPTwoRB.setText("Two");

        buttonGroup2.add(qTwoPThreeRB);
        qTwoPThreeRB.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        qTwoPThreeRB.setText("Three");

        buttonGroup2.add(qTwoPFourRB);
        qTwoPFourRB.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        qTwoPFourRB.setText("Four");

        buttonGroup2.add(qTwoPFiveRB);
        qTwoPFiveRB.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        qTwoPFiveRB.setText("Five");

        jLabel3.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jLabel3.setText("Review your peer performance for Implementation");

        buttonGroup3.add(qThreePOneRB);
        qThreePOneRB.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        qThreePOneRB.setText("One");

        buttonGroup3.add(qThreePTwoRB);
        qThreePTwoRB.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        qThreePTwoRB.setText("Two");

        buttonGroup3.add(qThreePThreeRB);
        qThreePThreeRB.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        qThreePThreeRB.setText("Three");

        qThreePFourRB.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        qThreePFourRB.setText("Four");

        buttonGroup3.add(qThreePFiveRB);
        qThreePFiveRB.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        qThreePFiveRB.setText("Five");

        jLabel4.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jLabel4.setText("Review your peer's communication skills in the team");

        buttonGroup4.add(qFourPOneRB);
        qFourPOneRB.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        qFourPOneRB.setText("One");

        buttonGroup4.add(qFourPTwoRB);
        qFourPTwoRB.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        qFourPTwoRB.setText("Two");

        buttonGroup4.add(qFourPThreeRB);
        qFourPThreeRB.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        qFourPThreeRB.setText("Three");

        buttonGroup4.add(qFourPFourRB);
        qFourPFourRB.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        qFourPFourRB.setText("Four");

        buttonGroup4.add(qFourPFiveRB);
        qFourPFiveRB.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        qFourPFiveRB.setText("Five");

        jLabel5.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jLabel5.setText("Review your peer's ability to take responsibility");

        buttonGroup5.add(qFivePOneRB);
        qFivePOneRB.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        qFivePOneRB.setText("One");

        buttonGroup5.add(qFivePTwoRB);
        qFivePTwoRB.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        qFivePTwoRB.setText("Two");

        buttonGroup5.add(qFivePThreeRB);
        qFivePThreeRB.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        qFivePThreeRB.setText("Three");

        buttonGroup5.add(qFivePFourRB);
        qFivePFourRB.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        qFivePFourRB.setText("Four");

        buttonGroup5.add(qFivePFiveRB);
        qFivePFiveRB.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        qFivePFiveRB.setText("Five");

        jLabel6.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jLabel6.setText("The positive aspects of your peer");

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel7.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jLabel7.setText("The negative aspects of your peer");

        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        submitButton.setBackground(new java.awt.Color(120, 88, 161));
        submitButton.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitPeerReviewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jScrollPane1)
                                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(layout.createSequentialGroup()
                                                        .addComponent(qOnePOneRB)
                                                        .addGap(32, 32, 32)
                                                        .addComponent(qOnePTwoRB)
                                                        .addGap(41, 41, 41)
                                                        .addComponent(qOnePThreeRB)
                                                        .addGap(43, 43, 43)
                                                        .addComponent(qOnePFourRB)
                                                        .addGap(48, 48, 48)
                                                        .addComponent(qOnePFiveRB))
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                                                        .addComponent(qFivePOneRB)
                                                                                        .addGap(26, 26, 26)
                                                                                        .addComponent(qFivePTwoRB)
                                                                                        .addGap(37, 37, 37)
                                                                                        .addComponent(qFivePThreeRB)
                                                                                        .addGap(49, 49, 49)
                                                                                        .addComponent(qFivePFourRB)
                                                                                        .addGap(50, 50, 50)
                                                                                        .addComponent(qFivePFiveRB))
                                                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                .addComponent(qTwoPOneRB)
                                                                                                .addComponent(qThreePOneRB)
                                                                                                .addComponent(qFourPOneRB))
                                                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                                                                                .addGap(30, 30, 30)
                                                                                                                .addComponent(qThreePTwoRB)
                                                                                                                .addGap(38, 38, 38)
                                                                                                                .addComponent(qThreePThreeRB)
                                                                                                                .addGap(49, 49, 49)
                                                                                                                .addComponent(qThreePFourRB)
                                                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                                                .addComponent(qThreePFiveRB))
                                                                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                                                                                .addGap(32, 32, 32)
                                                                                                                .addComponent(qTwoPTwoRB)
                                                                                                                .addGap(39, 39, 39)
                                                                                                                .addComponent(qTwoPThreeRB)
                                                                                                                .addGap(45, 45, 45)
                                                                                                                .addComponent(qTwoPFourRB)
                                                                                                                .addGap(46, 46, 46)
                                                                                                                .addComponent(qTwoPFiveRB)))
                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                        .addGap(28, 28, 28)
                                                                                                        .addComponent(qFourPTwoRB)
                                                                                                        .addGap(38, 38, 38)
                                                                                                        .addComponent(qFourPThreeRB)
                                                                                                        .addGap(51, 51, 51)
                                                                                                        .addComponent(qFourPFourRB)
                                                                                                        .addGap(46, 46, 46)
                                                                                                        .addComponent(qFourPFiveRB)))))
                                                                        .addGap(0, 0, Short.MAX_VALUE)))
                                                        .addGap(83, 83, 83))
                                                .addComponent(jScrollPane2)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(submitButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(104, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(qOnePOneRB)
                                        .addComponent(qOnePTwoRB)
                                        .addComponent(qOnePThreeRB)
                                        .addComponent(qOnePFourRB)
                                        .addComponent(qOnePFiveRB))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(qTwoPOneRB)
                                        .addComponent(qTwoPTwoRB)
                                        .addComponent(qTwoPThreeRB)
                                        .addComponent(qTwoPFourRB)
                                        .addComponent(qTwoPFiveRB))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(qThreePOneRB)
                                        .addComponent(qThreePTwoRB)
                                        .addComponent(qThreePThreeRB)
                                        .addComponent(qThreePFourRB)
                                        .addComponent(qThreePFiveRB))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(qFourPOneRB)
                                        .addComponent(qFourPTwoRB)
                                        .addComponent(qFourPThreeRB)
                                        .addComponent(qFourPFourRB)
                                        .addComponent(qFourPFiveRB))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(qFivePOneRB)
                                        .addComponent(qFivePTwoRB)
                                        .addComponent(qFivePThreeRB)
                                        .addComponent(qFivePFourRB)
                                        .addComponent(qFivePFiveRB))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(submitButton, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                .addContainerGap())
        );
        pack();
    }// </editor-fold>

    private void qOnePOneRBActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void submitPeerReviewActionPerformed(java.awt.event.ActionEvent evt) {
        String context1 = jTextArea1.getText();
        String context2 = jTextArea2.getText();
        int question1 = 0;
        int question2 = 0;
        int question3 = 0;
        int question4 = 0;
        int question5 = 0;

        //Question-1
        if(qOnePFiveRB.isSelected()){
            question1 = 5;
        }
        else if(qOnePFourRB.isSelected()){
            question1 = 4;
        }
        else if(qOnePThreeRB.isSelected()){
            question1 = 3;
        }
        else if(qOnePTwoRB.isSelected()){
            question1 = 2;
        }
        else if(qOnePOneRB.isSelected()){
            question1 = 1;
        }

        //Question-2
        if(qTwoPFiveRB.isSelected()){
            question2 = 5;
        }
        else if(qTwoPFourRB.isSelected()){
            question2 = 4;
        }
        else if(qTwoPThreeRB.isSelected()){
            question2 = 3;
        }
        else if(qTwoPTwoRB.isSelected()){
            question2 = 2;
        }
        else if(qTwoPOneRB.isSelected()){
            question2 = 1;
        }

        //Question-3
        if(qThreePFiveRB.isSelected()){
            question3 = 5;
        }
        else if(qThreePFourRB.isSelected()){
            question3 = 4;
        }
        else if(qThreePThreeRB.isSelected()){
            question3 = 3;
        }
        else if(qThreePTwoRB.isSelected()){
            question3 = 2;
        }
        else if(qThreePOneRB.isSelected()){
            question3 = 1;
        }

        //Question-4
        if(qFourPTwoRB.isSelected()){
            question4 = 5;
        }
        else if(qFourPTwoRB.isSelected()){
            question4 = 4;
        }
        else if(qFourPTwoRB.isSelected()){
            question4 = 3;
        }
        else if(qFourPTwoRB.isSelected()){
            question4 = 2;
        }
        else if(qFourPOneRB.isSelected()){
            question4 = 1;
        }

        //Question-5
        if(qFivePFiveRB.isSelected()){
            question5 = 5;
        }
        else if(qFivePFourRB.isSelected()){
            question5 = 4;
        }
        else if(qFivePThreeRB.isSelected()){
            question5 = 3;
        }
        else if(qFivePTwoRB.isSelected()){
            question5 = 2;
        }
        else if(qFivePOneRB.isSelected()){
            question5 = 1;
        }

        Student s = studentRepository.findByUserId(newStudentId);
        Group g = groupRepository.findByGroupId(s.getGroupId());
        currentUser.reviewPeer(s,question1,question2,question3,question4,question5,context1,context2);
        studentRepository.save(s);
        studentRepository.save(currentUser);
        groupRepository.save(g);
        Class c = classRepository.findByClassId(g.getClassId());
        classRepository.save(c);
    }

    // Variables declaration - do not modify
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JRadioButton qFivePFiveRB;
    private javax.swing.JRadioButton qFivePFourRB;
    private javax.swing.JRadioButton qFivePOneRB;
    private javax.swing.JRadioButton qFivePThreeRB;
    private javax.swing.JRadioButton qFivePTwoRB;
    private javax.swing.JRadioButton qFourPFiveRB;
    private javax.swing.JRadioButton qFourPFourRB;
    private javax.swing.JRadioButton qFourPOneRB;
    private javax.swing.JRadioButton qFourPThreeRB;
    private javax.swing.JRadioButton qFourPTwoRB;
    private javax.swing.JRadioButton qOnePFiveRB;
    private javax.swing.JRadioButton qOnePFourRB;
    private javax.swing.JRadioButton qOnePOneRB;
    private javax.swing.JRadioButton qOnePThreeRB;
    private javax.swing.JRadioButton qOnePTwoRB;
    private javax.swing.JRadioButton qThreePFiveRB;
    private javax.swing.JRadioButton qThreePFourRB;
    private javax.swing.JRadioButton qThreePOneRB;
    private javax.swing.JRadioButton qThreePThreeRB;
    private javax.swing.JRadioButton qThreePTwoRB;
    private javax.swing.JRadioButton qTwoPFiveRB;
    private javax.swing.JRadioButton qTwoPFourRB;
    private javax.swing.JRadioButton qTwoPOneRB;
    private javax.swing.JRadioButton qTwoPThreeRB;
    private javax.swing.JRadioButton qTwoPTwoRB;
    private javax.swing.JButton submitButton;
    // End of variables declaration
}
