package cs319.group1e.procheck319;

import javax.swing.*;
import java.awt.*;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author bedir
 */
public class GroupGUI extends javax.swing.JFrame {

    private Student currentUser;
    private GroupRepository groupRepository;
    private ClassRepository classRepository;
    private StudentRepository studentRepository;
    private String goTo;
    private int peer;
    private int artifactReviewId;
    private Submission sub;


    /**
     * Creates new form procheckGUI
     */
    public GroupGUI(StudentRepository studentRepository,  GroupRepository groupRepository, ClassRepository classRepository, Student currentUser) {
        this.groupRepository = groupRepository;
        this.classRepository = classRepository;
        this.studentRepository = studentRepository;
        setCurrentUser( currentUser );
        initComponents();
    }

    public void setSub(Submission sub){
        this.sub = sub;
    }
    public Submission getSub(){
        return sub;
    }
    public void setCurrentUser(Student currentUser) {
        this.currentUser = currentUser;
    }

    public int getPeer() {
        return peer;
    }
    public void setPeer(int peer) {
        this.peer = peer;
    }

    public Student getCurrentUser() {
        return currentUser;
    }

    public int getArtifactReviewId() {
        return artifactReviewId;
    }
    public void setArtifactReviewId(int artifactReviewId) {
        this.artifactReviewId = artifactReviewId;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        overallProgressPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        groupMemberPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        groupMemberLabel5 = new javax.swing.JLabel();
        groupMemberLabel1 = new javax.swing.JLabel();
        groupMemberLabel2 = new javax.swing.JLabel();
        groupMemberLabel3 = new javax.swing.JLabel();
        groupMemberLabel4 = new javax.swing.JLabel();
        groupMemberButton1 = new javax.swing.JButton();
        groupMemberButton2 = new javax.swing.JButton();
        groupMemberButton3 = new javax.swing.JButton();
        groupMemberButton4 = new javax.swing.JButton();
        groupMemberButton5 = new javax.swing.JButton();
        projectSummaryPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        headerPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        launchDatePanel = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        otherGroupsPanel = new javax.swing.JPanel();
        calendarPanel = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        statisticsPanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        viewARButton1 = new javax.swing.JButton();
        viewFeedbackButton1 = new javax.swing.JButton();
        announcementsPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        deadlinesPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        upcomingDeadlinesLabel5 = new javax.swing.JLabel();
        upcomingDeadlinesLabel3 = new javax.swing.JLabel();
        upcomingDeadlinesLabel4 = new javax.swing.JLabel();
        upcomingDeadlinesLabel1 = new javax.swing.JLabel();
        upcomingDeadlinesLabel2 = new javax.swing.JLabel();
        submitButton2 = new javax.swing.JButton();
        submitButton1 = new javax.swing.JButton();
        submitButton4 = new javax.swing.JButton();
        submitButton5 = new javax.swing.JButton();
        submitButton3 = new javax.swing.JButton();
        requestLabel1 = new javax.swing.JLabel();
        acceptButton1 = new javax.swing.JButton();

        overallProgressPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        groupMemberPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        groupMemberLabel5 = new javax.swing.JLabel();
        groupMemberLabel1 = new javax.swing.JLabel();
        groupMemberLabel2 = new javax.swing.JLabel();
        groupMemberLabel3 = new javax.swing.JLabel();
        groupMemberLabel4 = new javax.swing.JLabel();
        groupMemberButton1 = new javax.swing.JButton();
        groupMemberButton2 = new javax.swing.JButton();
        groupMemberButton3 = new javax.swing.JButton();
        groupMemberButton4 = new javax.swing.JButton();
        groupMemberButton5 = new javax.swing.JButton();
        projectSummaryPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        headerPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        launchDatePanel = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        otherGroupsPanel = new javax.swing.JPanel();
        artifactReviewMainLabel = new javax.swing.JLabel();
        randomArtifactButton = new javax.swing.JButton();
        artifactReviewURLLabel = new javax.swing.JLabel();
        artifactURLField = new javax.swing.JTextField();
        artifactReviewLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        artifactReviewArea = new javax.swing.JTextArea();
        firstArtifactCheckBox = new javax.swing.JCheckBox();
        secondArtifactCheckBox = new javax.swing.JCheckBox();
        submitArtifactButton = new javax.swing.JButton();
        calendarPanel = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        requestLabel1 = new javax.swing.JLabel();
        acceptButton1 = new javax.swing.JButton();
        statisticsPanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        viewARButton1 = new javax.swing.JButton();
        viewFeedbackButton1 = new javax.swing.JButton();
        announcementsPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        deadlinesPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        upcomingDeadlinesLabel5 = new javax.swing.JLabel();
        upcomingDeadlinesLabel3 = new javax.swing.JLabel();
        upcomingDeadlinesLabel4 = new javax.swing.JLabel();
        upcomingDeadlinesLabel1 = new javax.swing.JLabel();
        upcomingDeadlinesLabel2 = new javax.swing.JLabel();
        submitButton2 = new javax.swing.JButton();
        submitButton1 = new javax.swing.JButton();
        submitButton4 = new javax.swing.JButton();
        submitButton5 = new javax.swing.JButton();
        submitButton3 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        overallProgressPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        groupMemberPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        groupMemberLabel5 = new javax.swing.JLabel();
        groupMemberLabel1 = new javax.swing.JLabel();
        groupMemberLabel2 = new javax.swing.JLabel();
        groupMemberLabel3 = new javax.swing.JLabel();
        groupMemberLabel4 = new javax.swing.JLabel();
        groupMemberButton1 = new javax.swing.JButton();
        groupMemberButton2 = new javax.swing.JButton();
        groupMemberButton3 = new javax.swing.JButton();
        groupMemberButton4 = new javax.swing.JButton();
        groupMemberButton5 = new javax.swing.JButton();
        projectSummaryPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        headerPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        launchDatePanel = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        otherGroupsPanel = new javax.swing.JPanel();
        artifactReviewMainLabel = new javax.swing.JLabel();
        randomArtifactButton = new javax.swing.JButton();
        artifactReviewURLLabel = new javax.swing.JLabel();
        artifactURLField = new javax.swing.JTextField();
        artifactReviewLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        artifactReviewArea = new javax.swing.JTextArea();
        firstArtifactCheckBox = new javax.swing.JCheckBox();
        secondArtifactCheckBox = new javax.swing.JCheckBox();
        submitArtifactButton = new javax.swing.JButton();
        calendarPanel = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        requestLabel1 = new javax.swing.JLabel();
        acceptButton1 = new javax.swing.JButton();
        statisticsPanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        viewARButton1 = new javax.swing.JButton();
        viewFeedbackButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        feedbeackArea = new javax.swing.JTextArea();
        announcementsPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        deadlinesPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        upcomingDeadlinesLabel5 = new javax.swing.JLabel();
        upcomingDeadlinesLabel3 = new javax.swing.JLabel();
        upcomingDeadlinesLabel4 = new javax.swing.JLabel();
        upcomingDeadlinesLabel1 = new javax.swing.JLabel();
        upcomingDeadlinesLabel2 = new javax.swing.JLabel();
        submitButton2 = new javax.swing.JButton();
        submitButton1 = new javax.swing.JButton();
        submitButton4 = new javax.swing.JButton();
        submitButton5 = new javax.swing.JButton();
        submitButton3 = new javax.swing.JButton();
        artifactReviewsFeedback = new javax.swing.JTextArea();


        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        overallProgressPanel.setBackground(new java.awt.Color(232, 235, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Overall Progress");

        javax.swing.GroupLayout overallProgressPanelLayout = new javax.swing.GroupLayout(overallProgressPanel);
        overallProgressPanel.setLayout(overallProgressPanelLayout);
        overallProgressPanelLayout.setHorizontalGroup(
                overallProgressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, overallProgressPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                                .addContainerGap())
        );
        overallProgressPanelLayout.setVerticalGroup(
                overallProgressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(overallProgressPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        groupMemberPanel.setBackground(new java.awt.Color(232, 235, 255));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Group Members");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);


        /*

         */
        groupMemberLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        groupMemberLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        groupMemberLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        groupMemberLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        groupMemberLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        //groupMemberLabel5.setText("");



        Group groupM = groupRepository.findByGroupId(currentUser.getGroupId());
        if(groupM.getStudentIdList().size() >= 5) {
            Student m5 = studentRepository.findByUserId(groupM.getStudentIdList().get(4));
            if(m5 == null){
                groupMemberLabel5.setText("");
            }else{
                groupMemberLabel5.setText(m5.getUserName());

            }
        }


        //groupMemberLabel1.setText("");
        if(groupM.getStudentIdList().size() >= 1) {
            Student m1 = studentRepository.findByUserId(groupM.getStudentIdList().get(0));
            if(m1 == null){
                groupMemberLabel1.setText("");
            }else{
                groupMemberLabel1.setText(m1.getUserName());
            }
        }

        //groupMemberLabel2.setText("");
        if(groupM.getStudentIdList().size() >= 2) {
            Student m2 = studentRepository.findByUserId(groupM.getStudentIdList().get(1));
            if(m2 == null){
                groupMemberLabel2.setText("");
            }else{
                groupMemberLabel2.setText(m2.getUserName());
            }
        }

        //groupMemberLabel3.setText("");
        if(groupM.getStudentIdList().size() >=3) {
            Student m3 = studentRepository.findByUserId(groupM.getStudentIdList().get(2));
            if(m3 == null){
                groupMemberLabel3.setText("");
            }else{
                groupMemberLabel3.setText(m3.getUserName());
            }
        }

        //groupMemberLabel4.setText("");
        if(groupM.getStudentIdList().size() >= 4 ) {
            Student m4 = studentRepository.findByUserId(groupM.getStudentIdList().get(3));
            if(m4 == null){
                groupMemberLabel4.setText("");
            }else{
                groupMemberLabel4.setText(m4.getUserName());
            }
        }

        groupMemberButton1.setBackground(new java.awt.Color(120, 88, 161));
        groupMemberButton1.setForeground(new java.awt.Color(255, 255, 255));
        groupMemberButton1.setText("Review Peer");
        groupMemberButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                groupMemberButton1ActionPerformed(evt);
            }
        });

        groupMemberButton2.setBackground(new java.awt.Color(120, 88, 161));
        groupMemberButton2.setForeground(new java.awt.Color(255, 255, 255));
        groupMemberButton2.setText("Review Peer");
        groupMemberButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                groupMemberButton2ActionPerformed(evt);
            }
        });

        groupMemberButton3.setBackground(new java.awt.Color(120, 88, 161));
        groupMemberButton3.setForeground(new java.awt.Color(255, 255, 255));
        groupMemberButton3.setText("Review Peer");
        groupMemberButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                groupMemberButton3ActionPerformed(evt);
            }
        });

        groupMemberButton4.setBackground(new java.awt.Color(120, 88, 161));
        groupMemberButton4.setForeground(new java.awt.Color(255, 255, 255));
        groupMemberButton4.setText("Review Peer");
        groupMemberButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                groupMemberButton4ActionPerformed(evt);
            }
        });

        groupMemberButton5.setBackground(new java.awt.Color(120, 88, 161));
        groupMemberButton5.setForeground(new java.awt.Color(255, 255, 255));
        groupMemberButton5.setText("Review Peer");
        groupMemberButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                groupMemberButton5ActionPerformed(evt);
            }
        });
        javax.swing.GroupLayout groupMemberPanelLayout = new javax.swing.GroupLayout(groupMemberPanel);
        groupMemberPanel.setLayout(groupMemberPanelLayout);
        groupMemberPanelLayout.setHorizontalGroup(
                groupMemberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(groupMemberPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(groupMemberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(groupMemberPanelLayout.createSequentialGroup()
                                                .addComponent(groupMemberLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE))
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                                        .addGroup(groupMemberPanelLayout.createSequentialGroup()
                                                .addGroup(groupMemberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(groupMemberLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(groupMemberLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(groupMemberLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(groupMemberLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(68, 68, 68)
                                                .addGroup(groupMemberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(groupMemberButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(groupMemberButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(groupMemberButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(groupMemberButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(groupMemberButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
        );
        groupMemberPanelLayout.setVerticalGroup(
                groupMemberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(groupMemberPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(groupMemberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(groupMemberButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(groupMemberLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(groupMemberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(groupMemberLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                        .addComponent(groupMemberButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(groupMemberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(groupMemberButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(groupMemberPanelLayout.createSequentialGroup()
                                                .addGap(29, 29, 29)
                                                .addComponent(jLabel4))
                                        .addComponent(groupMemberLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(groupMemberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(groupMemberButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(groupMemberLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(groupMemberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(groupMemberLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(groupMemberButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                                .addGap(55, 55, 55))
        );

        projectSummaryPanel.setBackground(new java.awt.Color(232, 235, 255));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Project Summary");

        javax.swing.GroupLayout projectSummaryPanelLayout = new javax.swing.GroupLayout(projectSummaryPanel);
        projectSummaryPanel.setLayout(projectSummaryPanelLayout);
        projectSummaryPanelLayout.setHorizontalGroup(
                projectSummaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(projectSummaryPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );
        projectSummaryPanelLayout.setVerticalGroup(
                projectSummaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(projectSummaryPanelLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel5)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        headerPanel.setBackground(new java.awt.Color(232, 235, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Assignment Process");

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
                headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(headerPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1292, Short.MAX_VALUE))
        );
        headerPanelLayout.setVerticalGroup(
                headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(headerPanelLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 0, Short.MAX_VALUE))
        );

        launchDatePanel.setBackground(new java.awt.Color(232, 235, 255));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Projected Launch Date");

        javax.swing.GroupLayout launchDatePanelLayout = new javax.swing.GroupLayout(launchDatePanel);
        launchDatePanel.setLayout(launchDatePanelLayout);
        launchDatePanelLayout.setHorizontalGroup(
                launchDatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(launchDatePanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                                .addContainerGap())
        );
        launchDatePanelLayout.setVerticalGroup(
                launchDatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(launchDatePanelLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel10)
                                .addContainerGap(109, Short.MAX_VALUE))
        );

        //****************************************************************************

        //OLD VERSION PART

        //***********************************************************************************

        //ARTIFACT REVIEW PANEL --> OLD otherGroupsPanel
        otherGroupsPanel.setBackground(new java.awt.Color(232, 235, 255));

        artifactReviewMainLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        artifactReviewMainLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        artifactReviewMainLabel.setText("Artifact Review");

        randomArtifactButton.setBackground(new java.awt.Color(120, 88, 161));
        randomArtifactButton.setForeground(new java.awt.Color(255, 255, 255));
        randomArtifactButton.setText("Review Random Artifact");
        randomArtifactButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                randomArtifactButtonActionPerformed(evt);
            }
        });

        artifactReviewURLLabel.setText("URL: ");

        artifactURLField.setEditable(false);
        artifactURLField.setText("Press \"Review Random Artifact\" Button First");

        artifactReviewLabel.setText("Write Your Feedback: ");

        artifactReviewArea.setColumns(20);
        artifactReviewArea.setRows(5);
        artifactReviewArea.setEnabled(false);
        jScrollPane1.setViewportView(artifactReviewArea);

        firstArtifactCheckBox.setText("First Artifact Review State");
        firstArtifactCheckBox.setEnabled(false);

        secondArtifactCheckBox.setText("Second Artifact Review State");
        secondArtifactCheckBox.setEnabled(false);

        submitArtifactButton.setBackground(new java.awt.Color(120, 88, 161));
        submitArtifactButton.setForeground(new java.awt.Color(255, 255, 255));
        submitArtifactButton.setText("Submit Review");
        submitArtifactButton.setEnabled(false);
        submitArtifactButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitArtifactButtonActionPerformed(evt);
            }
        });

        //*****************************************************************************
        javax.swing.GroupLayout otherGroupsPanelLayout = new javax.swing.GroupLayout(otherGroupsPanel);
        otherGroupsPanel.setLayout(otherGroupsPanelLayout);
        otherGroupsPanelLayout.setHorizontalGroup(
                otherGroupsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(otherGroupsPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(otherGroupsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(otherGroupsPanelLayout.createSequentialGroup()
                                                .addGroup(otherGroupsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(artifactReviewMainLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addGroup(otherGroupsPanelLayout.createSequentialGroup()
                                                                .addComponent(artifactReviewURLLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(artifactURLField))
                                                        .addGroup(otherGroupsPanelLayout.createSequentialGroup()
                                                                .addGroup(otherGroupsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                        .addComponent(firstArtifactCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(artifactReviewLabel)
                                                                        .addComponent(secondArtifactCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                                .addGap(0, 134, Short.MAX_VALUE)))
                                                .addContainerGap())
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, otherGroupsPanelLayout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(randomArtifactButton, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(45, 45, 45))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, otherGroupsPanelLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(submitArtifactButton, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21))
        );
        otherGroupsPanelLayout.setVerticalGroup(
                otherGroupsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(otherGroupsPanelLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(artifactReviewMainLabel)
                                .addGap(18, 18, 18)
                                .addComponent(randomArtifactButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(otherGroupsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(artifactReviewURLLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(artifactURLField, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(artifactReviewLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(firstArtifactCheckBox)
                                .addGap(18, 18, 18)
                                .addComponent(secondArtifactCheckBox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(submitArtifactButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36))
        );


        //REQUEST PANEL
        calendarPanel.setBackground(new java.awt.Color(232, 235, 255));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Requests");

        requestLabel1.setText("Student's Request Can Be Seen From Here ------->");

        acceptButton1.setBackground(new java.awt.Color(120, 88, 161));
        acceptButton1.setForeground(new java.awt.Color(255, 255, 255));
        acceptButton1.setText("View Request");
        acceptButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout calendarPanelLayout = new javax.swing.GroupLayout(calendarPanel);
        calendarPanel.setLayout(calendarPanelLayout);
        calendarPanelLayout.setHorizontalGroup(
                calendarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(calendarPanelLayout.createSequentialGroup()
                                .addGap(131, 131, 131)
                                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                                .addGap(137, 137, 137))
                        .addGroup(calendarPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(calendarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(requestLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(calendarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(acceptButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                )
                                .addGap(18, 18, 18)
                                .addGroup(calendarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        calendarPanelLayout.setVerticalGroup(
                calendarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(calendarPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addGroup(calendarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(requestLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(acceptButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(calendarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)

                                )
                                .addGap(18, 18, 18)
                                .addGroup(calendarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)

                                )
                                .addGap(18, 18, 18)
                                .addGroup(calendarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                )
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        statisticsPanel.setBackground(new java.awt.Color(232, 235, 255));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("View Reviews");

        viewARButton1.setBackground(new java.awt.Color(120, 88, 161));
        viewARButton1.setForeground(new java.awt.Color(255, 255, 255));
        viewARButton1.setText("View Artifact Review");
        viewARButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewARButton1ActionPerformed(evt);
            }
        });

        viewFeedbackButton1.setBackground(new java.awt.Color(120, 88, 161));
        viewFeedbackButton1.setForeground(new java.awt.Color(255, 255, 255));
        viewFeedbackButton1.setText("View Feedbacks");
        viewFeedbackButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewFeedbackButton1ActionPerformed(evt);
            }
        });


        artifactReviewsFeedback.setEditable(false);
        artifactReviewsFeedback.setColumns(20);
        artifactReviewsFeedback.setRows(5);
        jScrollPane2.setViewportView(artifactReviewsFeedback);

        feedbeackArea.setEditable(false);
        feedbeackArea.setColumns(20);
        feedbeackArea.setRows(5);
        jScrollPane3.setViewportView(feedbeackArea);

        javax.swing.GroupLayout statisticsPanelLayout = new javax.swing.GroupLayout(statisticsPanel);
        statisticsPanel.setLayout(statisticsPanelLayout);
        statisticsPanelLayout.setHorizontalGroup(
                statisticsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(statisticsPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(statisticsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(statisticsPanelLayout.createSequentialGroup()
                                                .addGroup(statisticsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(viewARButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(statisticsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(viewFeedbackButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE))))
                                .addContainerGap())
        );
        statisticsPanelLayout.setVerticalGroup(
                statisticsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(statisticsPanelLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addGroup(statisticsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(viewARButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                                        .addComponent(viewFeedbackButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(statisticsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                                        .addComponent(jScrollPane3))
                                .addContainerGap())
        );

        //-----------------------------------------------------------ANNOUNCEMENT PART STARTS-----------------------------------------------------------
        announcementsPanel.setBackground(new java.awt.Color(232, 235, 255));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Announcements");

        Class c = classRepository.findByClassId(319);
        List<Announcement> announcements = c.getAnnouncementList();
        String anno = "";
        if(announcements.size() > 0){
            for(int i = 0; i < announcements.size(); i++){
                anno += "\n" + announcements.get(i);
            }
        }

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText(anno);
        jScrollPane4.setViewportView(jTextArea1);

        javax.swing.GroupLayout announcementsPanelLayout = new javax.swing.GroupLayout(announcementsPanel);
        announcementsPanel.setLayout(announcementsPanelLayout);
        announcementsPanelLayout.setHorizontalGroup(
                announcementsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(announcementsPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
                                .addContainerGap())
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        announcementsPanelLayout.setVerticalGroup(
                announcementsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(announcementsPanelLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane4)
                                .addContainerGap()));

        deadlinesPanel.setBackground(new java.awt.Color(232, 235, 255));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Upcoming Deadlines");


        Class classA = classRepository.findByClassId(319);
        List<Assignment> assignmentsA = classA.getProject().getAssignmentList();
        upcomingDeadlinesLabel5.setText(assignmentsA.get(4).getTitle());

        upcomingDeadlinesLabel3.setText(assignmentsA.get(2).getTitle());

        upcomingDeadlinesLabel4.setText(assignmentsA.get(3).getTitle());

        upcomingDeadlinesLabel1.setText(assignmentsA.get(0).getTitle());

        upcomingDeadlinesLabel2.setText(assignmentsA.get(1).getTitle());


        submitButton2.setBackground(new java.awt.Color(120, 88, 161));
        submitButton2.setForeground(new java.awt.Color(255, 255, 255));
        submitButton2.setText("Make Submission");
        submitButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButton2ActionPerformed(evt);
            }
        });

        submitButton1.setBackground(new java.awt.Color(120, 88, 161));
        submitButton1.setForeground(new java.awt.Color(255, 255, 255));
        submitButton1.setText("Make Submission");
        submitButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButton1ActionPerformed(evt);
            }
        });

        submitButton4.setBackground(new java.awt.Color(120, 88, 161));
        submitButton4.setForeground(new java.awt.Color(255, 255, 255));
        submitButton4.setText("Make Submission");
        submitButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButton4ActionPerformed(evt);
            }
        });

        submitButton5.setBackground(new java.awt.Color(120, 88, 161));
        submitButton5.setForeground(new java.awt.Color(255, 255, 255));
        submitButton5.setText("Make Submission");
        submitButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButton5ActionPerformed(evt);
            }
        });

        submitButton3.setBackground(new java.awt.Color(120, 88, 161));
        submitButton3.setForeground(new java.awt.Color(255, 255, 255));
        submitButton3.setText("Make Submission");
        submitButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButton3ActionPerformed(evt);
            }
        });

        jTextField1.setText("Submission Link");

        javax.swing.GroupLayout deadlinesPanelLayout = new javax.swing.GroupLayout(deadlinesPanel);
        deadlinesPanel.setLayout(deadlinesPanelLayout);
        deadlinesPanelLayout.setHorizontalGroup(
                deadlinesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deadlinesPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(deadlinesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jTextField1)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, deadlinesPanelLayout.createSequentialGroup()
                                                .addGroup(deadlinesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(upcomingDeadlinesLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(upcomingDeadlinesLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(upcomingDeadlinesLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(upcomingDeadlinesLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                                                        .addComponent(upcomingDeadlinesLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(deadlinesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(submitButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
                                                        .addComponent(submitButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(submitButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(submitButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(submitButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addContainerGap())
        );
        deadlinesPanelLayout.setVerticalGroup(
                deadlinesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(deadlinesPanelLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(deadlinesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(upcomingDeadlinesLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(submitButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(4, 4, 4)
                                .addGroup(deadlinesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(upcomingDeadlinesLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(submitButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(deadlinesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(upcomingDeadlinesLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(submitButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(deadlinesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(upcomingDeadlinesLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(submitButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(deadlinesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(upcomingDeadlinesLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(submitButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(overallProgressPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(18, 18, 18)
                                                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(projectSummaryPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(groupMemberPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                .addComponent(calendarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(statisticsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                .addComponent(announcementsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(deadlinesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(otherGroupsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(launchDatePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(launchDatePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(overallProgressPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(groupMemberPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(statisticsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(calendarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(projectSummaryPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(announcementsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(deadlinesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(otherGroupsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //REQUEST ACCEPT OR REJECT
    private void acceptButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_groupButton11ActionPerformed
        Group g = groupRepository.findByGroupId(currentUser.getGroupId());
        Class c = classRepository.findByClassId(319);
        Request request = new Request(g.getGroupId(), g.getRequests().get(0).getSenderStudentId());
        String info = "";
        if(request != null) {
            int studentId = request.getSenderStudentId();
            Student student = studentRepository.findByUserId(studentId);
            info = student.getUserName() + " " + student.getUserSurname() + " has send request to join your group";
            UIManager um = new UIManager();
            um.put("OptionPane.background", new Color(120, 88, 161));
            um.put("Panel.background", new Color(120, 88, 161));
            int result = JOptionPane.showConfirmDialog(null,info, "Join Request",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE);

            //Accept request
            if(result == JOptionPane.YES_OPTION) {
                g.addGroupMember(student);
                g.getRequests().remove(0);
                studentRepository.save(student);
                groupRepository.save(g);
                classRepository.save(c);
            }else{
                g.getRequests().remove(0);
                groupRepository.save(g);
                classRepository.save(c);
            }
        }

    }

    //GET A RANDOM ARTIFACT BY PRESSING THE BUTTON!!!!!!!!!!!!!!!!
    private void randomArtifactButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_groupButton1ActionPerformed
        if(firstArtifactCheckBox.isSelected() && secondArtifactCheckBox.isSelected()){
            firstArtifactCheckBox.setSelected(false);
            secondArtifactCheckBox.setSelected(false);
        }
        firstArtifactCheckBox.setSelected(true);
        List<Assignment> assignments = new ArrayList<>();
        Group g = groupRepository.findByGroupId(currentUser.getGroupId());
        assignments = groupRepository.findByGroupId(currentUser.getGroupId()).getGroupAssignmentList();
        this.sub = currentUser.getRandomArtifact(assignments,g);
        if(sub != null) {
            String url = sub.getUrl();
            artifactURLField.setEditable(false);
            artifactURLField.setText(url);
            artifactReviewArea.setEnabled(true);
            submitArtifactButton.setEnabled(true);
        }
        else {
            UIManager um=new UIManager();
            um.put("OptionPane.background",new Color(120, 88, 161));
            um.put("Panel.background",new Color(120, 88, 161));
            JOptionPane.showMessageDialog(null,"No Submission Available","Set Color",
                    JOptionPane.INFORMATION_MESSAGE);
        }
    }

    //SUBMIT THE JTEXTFIELD TO THE SYSTEM!!!!!!!!!!!
    private void submitArtifactButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_groupButton1ActionPerformed
        String context = artifactReviewArea.getText();
        ArtifactReview doneArtifactReview = currentUser.reviewArtifact(sub,context);
        if(firstArtifactCheckBox.isSelected()){
            secondArtifactCheckBox.setSelected(true);
        }
        firstArtifactCheckBox.setSelected(true);

        //Save to Class repo
        Class c = classRepository.findByClassId(319);
        List<Submission> submissions = c.getProject().getAssignmentList().get(sub.getAssignmentNo()-1).getSubmissionList();
        for(int i = 0; i < submissions.size(); i++){
            if(submissions.get(i).getGroupId() == sub.getGroupId()){
                submissions.get(i).getArtifactReviews().add(doneArtifactReview);
            }
        }
        classRepository.save(c);

        //Save to group's submission
        Group group = groupRepository.findByGroupId(sub.getGroupId());
        for(int i = 0; i < group.getGroupSubmissionList().size(); i++) {
            if(sub.getAssignmentNo() == group.getGroupSubmissionList().get(i).getAssignmentNo()) {
                group.getGroupSubmissionList().get(i).getArtifactReviews().add(doneArtifactReview);
            }
        }
        groupRepository.save(group);
    }


    public String getGoTo() {
        return goTo;
    }

    public void setGoTo(String goTo) {
        this.goTo = goTo;
    }

    private void viewARButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_groupButton1ActionPerformed
        Group g = groupRepository.findByGroupId(currentUser.getGroupId());
        List<Submission> submissions = g.getGroupSubmissionList();
        String text = "";
        for(int i = 0; i < submissions.size(); i++) {
            for( int j = 0; j < submissions.get(i).getArtifactReviews().size(); j++) {
                text += "\nArtifact Review for " + submissions.get(i).getAssignmentNo() + ": " + submissions.get(i).getArtifactReviews().get(j);
            }
        }
        artifactReviewsFeedback.setText(text);
    }

    private void viewFeedbackButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_groupButton1ActionPerformed
        Group g = groupRepository.findByGroupId(currentUser.getGroupId());
        List<Submission> submissions = g.getGroupSubmissionList();
        String text = "";
        for(int i = 0; i < submissions.size(); i++) {
            for( int j = 0; j < submissions.get(i).getArtifactReviews().size(); j++) {
                text += "\n" + submissions.get(i).getFeedback();
            }
        }
        feedbeackArea.setText(text);
    }

    private void submitButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_groupButton1ActionPerformed
        //POP UP FIFTH SUBMISSON PAGE WITH GITHUB LINK FIELD
        Assignment assignment = classRepository.findByClassId(319).getProject().getAssignmentList().get(0);
        String context = jTextField1.getText();
        Class c = classRepository.findByClassId(319);
        Submission submission = new Submission(assignment,context);
        c.getProject().getAssignmentList().get(0).addSubmission(submission);
        Group group = groupRepository.findByGroupId(currentUser.getGroupId());
        currentUser.addSubmission(submission,assignment,group);
        Student s = studentRepository.findByUserId(currentUser.getUserId());
        studentRepository.save(s);
        groupRepository.save(group);
        classRepository.save(c);
    }

    private void submitButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_groupButton1ActionPerformed
        //POP UP FIRST SUBMISSON PAGE WITH GITHUB LINK FIELD
        Assignment assignment = classRepository.findByClassId(319).getProject().getAssignmentList().get(1);
        String context = jTextField1.getText();
        Class c = classRepository.findByClassId(319);
        Submission submission = new Submission(assignment,context);
        c.getProject().getAssignmentList().get(1).addSubmission(submission);
        Group group = groupRepository.findByGroupId(currentUser.getGroupId());
        currentUser.addSubmission(submission,assignment,group);
        Student s = studentRepository.findByUserId(currentUser.getUserId());
        studentRepository.save(s);
        groupRepository.save(group);
        classRepository.save(c);
    }

    private void submitButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_groupButton1ActionPerformed
        //POP UP SECOND SUBMISSON PAGE WITH GITHUB LINK FIELD
        Assignment assignment = classRepository.findByClassId(319).getProject().getAssignmentList().get(2);
        String context = jTextField1.getText();
        Class c = classRepository.findByClassId(319);
        Submission submission = new Submission(assignment,context);
        c.getProject().getAssignmentList().get(2).addSubmission(submission);
        Group group = groupRepository.findByGroupId(currentUser.getGroupId());
        currentUser.addSubmission(submission,assignment,group);
        Student s = studentRepository.findByUserId(currentUser.getUserId());
        studentRepository.save(s);
        groupRepository.save(group);
        classRepository.save(c);
    }

    private void submitButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_groupButton1ActionPerformed
        //POP UP THIRD SUBMISSON PAGE WITH GITHUB LINK FIELD
        Assignment assignment = classRepository.findByClassId(319).getProject().getAssignmentList().get(3);
        String context = jTextField1.getText();
        Class c = classRepository.findByClassId(319);
        Submission submission = new Submission(assignment,context);
        c.getProject().getAssignmentList().get(3).addSubmission(submission);
        Group group = groupRepository.findByGroupId(currentUser.getGroupId());
        currentUser.addSubmission(submission,assignment,group);
        Student s = studentRepository.findByUserId(currentUser.getUserId());
        studentRepository.save(s);
        groupRepository.save(group);
        classRepository.save(c);
    }

    private void submitButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_groupButton1ActionPerformed
        //POP UP FORTH SUBMISSON PAGE WITH GITHUB LINK FIELD
        Assignment assignment = classRepository.findByClassId(319).getProject().getAssignmentList().get(4);
        String context = jTextField1.getText();
        Class c = classRepository.findByClassId(319);
        Submission submission = new Submission(assignment,context);
        c.getProject().getAssignmentList().get(4).addSubmission(submission);
        Group group = groupRepository.findByGroupId(currentUser.getGroupId());
        currentUser.addSubmission(submission,assignment,group);
        Student s = studentRepository.findByUserId(currentUser.getUserId());
        studentRepository.save(s);
        groupRepository.save(group);
        classRepository.save(c);
    }

    //Peer Review for Group Member 1
    private void groupMemberButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_groupButton1ActionPerformed
        // TODO add your handling code here:
        Group g = groupRepository.findByGroupId(currentUser.getGroupId());
        int id = g.getStudentIdList().get(0);
        Student s = studentRepository.findByUserId(id);
        if(g.getStudentIdList().size() <= 1 || s.getUserId() == currentUser.getUserId()){
            UIManager um=new UIManager();
            um.put("OptionPane.background",new Color(120, 88, 161));
            um.put("Panel.background",new Color(120, 88, 161));
            JOptionPane.showMessageDialog(null,"Invalid review","Set Color",
                    JOptionPane.INFORMATION_MESSAGE);
        }
        else {
            peer = s.getUserId();
            goTo = "PeerReview";
        }
    }

    private void groupMemberButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_groupButton1ActionPerformed
        // TODO add your handling code here:
        Group g = groupRepository.findByGroupId(currentUser.getGroupId());
        int id = g.getStudentIdList().get(1);
        Student s = studentRepository.findByUserId(id);
        if(g.getStudentIdList().size() <= 1 || s.getUserId() == currentUser.getUserId()){
            UIManager um=new UIManager();
            um.put("OptionPane.background",new Color(120, 88, 161));
            um.put("Panel.background",new Color(120, 88, 161));
            JOptionPane.showMessageDialog(null,"Invalid review","Set Color",
                    JOptionPane.INFORMATION_MESSAGE);
        }
        else {
            peer = s.getUserId();
            goTo = "PeerReview";
        }
    }

    private void groupMemberButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_groupButton1ActionPerformed
        // TODO add your handling code here:
        Group g = groupRepository.findByGroupId(currentUser.getGroupId());
        int id = g.getStudentIdList().get(2);
        Student s = studentRepository.findByUserId(id);
        if(g.getStudentIdList().size() <= 1 || s.getUserId() == currentUser.getUserId()){
            UIManager um=new UIManager();
            um.put("OptionPane.background",new Color(120, 88, 161));
            um.put("Panel.background",new Color(120, 88, 161));
            JOptionPane.showMessageDialog(null,"Invalid review","Set Color",
                    JOptionPane.INFORMATION_MESSAGE);
        }
        else {
            peer = s.getUserId();
            goTo = "PeerReview";
        }
    }

    private void groupMemberButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_groupButton1ActionPerformed
        // TODO add your handling code here:
        Group g = groupRepository.findByGroupId(currentUser.getGroupId());
        int id = g.getStudentIdList().get(3);
        Student s = studentRepository.findByUserId(id);
        if(g.getStudentIdList().size() <= 1 || s.getUserId() == currentUser.getUserId()){
            UIManager um=new UIManager();
            um.put("OptionPane.background",new Color(120, 88, 161));
            um.put("Panel.background",new Color(120, 88, 161));
            JOptionPane.showMessageDialog(null,"Invalid review","Set Color",
                    JOptionPane.INFORMATION_MESSAGE);
        }
        else {
            peer = s.getUserId();
            goTo = "PeerReview";
        }
    }

    private void groupMemberButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_groupButton1ActionPerformed
        // TODO add your handling code here:
        Group g = groupRepository.findByGroupId(currentUser.getGroupId());
        int id = g.getStudentIdList().get(4);
        Student s = studentRepository.findByUserId(id);
        if(g.getStudentIdList().size() <= 1 || s.getUserId() == currentUser.getUserId()){
            UIManager um=new UIManager();
            um.put("OptionPane.background",new Color(120, 88, 161));
            um.put("Panel.background",new Color(120, 88, 161));
            JOptionPane.showMessageDialog(null,"Invalid review","Set Color",
                    JOptionPane.INFORMATION_MESSAGE);
        }
        else {
            peer = s.getUserId();
            goTo = "PeerReview";
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel announcementsPanel;
    private javax.swing.JPanel calendarPanel;
    private javax.swing.JPanel deadlinesPanel;
    private javax.swing.JButton groupMemberButton1;
    private javax.swing.JButton groupMemberButton2;
    private javax.swing.JButton groupMemberButton3;
    private javax.swing.JButton groupMemberButton4;
    private javax.swing.JButton groupMemberButton5;
    private javax.swing.JLabel groupMemberLabel1;
    private javax.swing.JLabel groupMemberLabel2;
    private javax.swing.JLabel groupMemberLabel3;
    private javax.swing.JLabel groupMemberLabel4;
    private javax.swing.JLabel groupMemberLabel5;
    private javax.swing.JPanel groupMemberPanel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel launchDatePanel;
    private javax.swing.JPanel otherGroupsPanel;
    private javax.swing.JPanel overallProgressPanel;
    private javax.swing.JPanel projectSummaryPanel;
    private javax.swing.JPanel statisticsPanel;
    private javax.swing.JButton submitButton1;
    private javax.swing.JButton submitButton2;
    private javax.swing.JButton submitButton3;
    private javax.swing.JButton submitButton4;
    private javax.swing.JButton submitButton5;
    private javax.swing.JLabel upcomingDeadlinesLabel1;
    private javax.swing.JLabel upcomingDeadlinesLabel2;
    private javax.swing.JLabel upcomingDeadlinesLabel3;
    private javax.swing.JLabel upcomingDeadlinesLabel4;
    private javax.swing.JLabel upcomingDeadlinesLabel5;
    private javax.swing.JButton viewARButton1;
    private javax.swing.JButton viewFeedbackButton1;

    private javax.swing.JButton acceptButton1;
    private javax.swing.JLabel requestLabel1;
    private javax.swing.JTextArea artifactReviewArea;
    private javax.swing.JLabel artifactReviewLabel;
    private javax.swing.JLabel artifactReviewMainLabel;
    private javax.swing.JLabel artifactReviewURLLabel;
    private javax.swing.JTextField artifactURLField;
    private javax.swing.JCheckBox firstArtifactCheckBox;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton randomArtifactButton;
    private javax.swing.JCheckBox secondArtifactCheckBox;
    private javax.swing.JButton submitArtifactButton;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextArea feedbeackArea;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea artifactReviewsFeedback;

    // End of variables declaration//GEN-END:variables
}
