package cs319.group1e.procheck319;

import javax.swing.*;
import java.awt.*;
import java.util.List;

/**
 *
 * @author bedir
 */
class NoGroupGUI extends javax.swing.JFrame {

    private Student currentUser;
    private InstructorAndTAsRepository instructorAndTAsRepository;
    private StudentRepository studentRepository;
    private GroupRepository groupRepository;
    private ClassRepository classRepository;

    //Constructor
    public NoGroupGUI(InstructorAndTAsRepository instructorAndTAsRepository, StudentRepository studentRepository, GroupRepository groupRepository, ClassRepository classRepository) {
        this.studentRepository = studentRepository;
        this.instructorAndTAsRepository = instructorAndTAsRepository;
        this.groupRepository = groupRepository;
        this.classRepository = classRepository;
        initComponents();
    }

    public Student getCurrentUser() {
        return currentUser;
    }

    public void setCurrentUser(Student currentUser) {
        this.currentUser = currentUser;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        overallProgressPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        formNewGroupPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        projectSummaryPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        headerPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        launchDatePanel = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        otherGroupsPanel = new javax.swing.JPanel(); //GRUPLARI LİSTELE
        jLabel8 = new javax.swing.JLabel();
        calendarPanel = new javax.swing.JPanel();
        invitationsPanel = new javax.swing.JPanel(); //INVITATIONSLARI LİSTELE
        jLabel9 = new javax.swing.JLabel();
        announcementsPanel = new javax.swing.JPanel(); //ANNOUNCEMENTLERI LİSTELE
        jLabel6 = new javax.swing.JLabel();
        deadlinesPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        otherGroupsLabel1 = new javax.swing.JLabel();
        groupButton1 = new javax.swing.JButton();
        otherGroupsLabel4 = new javax.swing.JLabel();
        groupButton2 = new javax.swing.JButton();
        otherGroupsLabel2 = new javax.swing.JLabel();
        groupButton3 = new javax.swing.JButton();
        otherGroupsLabel3 = new javax.swing.JLabel();
        otherGroupsLabel7 = new javax.swing.JLabel();
        otherGroupsLabel5 = new javax.swing.JLabel();
        otherGroupsLabel8 = new javax.swing.JLabel();
        otherGroupsLabel10 = new javax.swing.JLabel();
        otherGroupsLabel6 = new javax.swing.JLabel();
        otherGroupsLabel11 = new javax.swing.JLabel();
        otherGroupsLabel9 = new javax.swing.JLabel();
        groupButton5 = new javax.swing.JButton();
        groupButton6 = new javax.swing.JButton();
        groupButton7 = new javax.swing.JButton();
        groupButton4 = new javax.swing.JButton();
        groupButton11 = new javax.swing.JButton();
        groupButton8 = new javax.swing.JButton();
        groupButton9 = new javax.swing.JButton();
        groupButton10 = new javax.swing.JButton();

        overallProgressPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        projectSummaryPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        headerPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        launchDatePanel = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        otherGroupsPanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        announcementsPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        deadlinesPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();



        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        overallProgressPanel.setBackground(new java.awt.Color(232, 235, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Overall Progress");

        javax.swing.GroupLayout overallProgressPanelLayout = new javax.swing.GroupLayout(overallProgressPanel);
        overallProgressPanel.setLayout(overallProgressPanelLayout);
        overallProgressPanelLayout.setHorizontalGroup(
                overallProgressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, overallProgressPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                                .addContainerGap())
        );
        overallProgressPanelLayout.setVerticalGroup(
                overallProgressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(overallProgressPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        formNewGroupPanel.setBackground(new java.awt.Color(232, 235, 255));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Form A New Group");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("You Can Form Your Own Group");

        jButton1.setText("Form A New Group");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout formNewGroupPanelLayout = new javax.swing.GroupLayout(formNewGroupPanel);
        formNewGroupPanel.setLayout(formNewGroupPanelLayout);
        formNewGroupPanelLayout.setHorizontalGroup(
                formNewGroupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(formNewGroupPanelLayout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(formNewGroupPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(formNewGroupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
        );
        formNewGroupPanelLayout.setVerticalGroup(
                formNewGroupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(formNewGroupPanelLayout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(125, 125, 125))
        );

        projectSummaryPanel.setBackground(new java.awt.Color(232, 235, 255));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Project Summary");

        javax.swing.GroupLayout projectSummaryPanelLayout = new javax.swing.GroupLayout(projectSummaryPanel);
        projectSummaryPanel.setLayout(projectSummaryPanelLayout);
        projectSummaryPanelLayout.setHorizontalGroup(
                projectSummaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(projectSummaryPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );
        projectSummaryPanelLayout.setVerticalGroup(
                projectSummaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(projectSummaryPanelLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel5)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        headerPanel.setBackground(new java.awt.Color(232, 235, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("You Are Not In A Group");

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
                headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(headerPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1292, Short.MAX_VALUE))
        );
        headerPanelLayout.setVerticalGroup(
                headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(headerPanelLayout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(46, Short.MAX_VALUE))
        );

        launchDatePanel.setBackground(new java.awt.Color(232, 235, 255));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Projected Launch Date");

        javax.swing.GroupLayout launchDatePanelLayout = new javax.swing.GroupLayout(launchDatePanel);
        launchDatePanel.setLayout(launchDatePanelLayout);
        launchDatePanelLayout.setHorizontalGroup(
                launchDatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(launchDatePanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                                .addContainerGap())
        );
        launchDatePanelLayout.setVerticalGroup(
                launchDatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(launchDatePanelLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel10)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        otherGroupsPanel.setBackground(new java.awt.Color(232, 235, 255));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Other Groups");

        otherGroupsLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        otherGroupsLabel1.setText("Group-1");

        groupButton1.setBackground(new java.awt.Color(120, 88, 161));
        groupButton1.setForeground(new java.awt.Color(255, 255, 255));
        groupButton1.setText("Send Request");
        groupButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                groupButton1ActionPerformed(evt);
            }
        });

        otherGroupsLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        otherGroupsLabel4.setText("Group-4");

        groupButton2.setBackground(new java.awt.Color(120, 88, 161));
        groupButton2.setForeground(new java.awt.Color(255, 255, 255));
        groupButton2.setText("Send Request");
        groupButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                groupButton2ActionPerformed(evt);
            }
        });

        otherGroupsLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        otherGroupsLabel2.setText("Group-2");

        groupButton3.setBackground(new java.awt.Color(120, 88, 161));
        groupButton3.setForeground(new java.awt.Color(255, 255, 255));
        groupButton3.setText("Send Request");
        groupButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                groupButton3ActionPerformed(evt);
            }
        });

        otherGroupsLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        otherGroupsLabel3.setText("Group-3");

        otherGroupsLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        otherGroupsLabel7.setText("Group-7");

        otherGroupsLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        otherGroupsLabel5.setText("Group-5");

        otherGroupsLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        otherGroupsLabel8.setText("Group-8");

        otherGroupsLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        otherGroupsLabel10.setText("Group-10");

        otherGroupsLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        otherGroupsLabel6.setText("Group-6");

        otherGroupsLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        otherGroupsLabel11.setText("Group-11");

        otherGroupsLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        otherGroupsLabel9.setText("Group-9");

        groupButton4.setBackground(new java.awt.Color(120, 88, 161));
        groupButton4.setForeground(new java.awt.Color(255, 255, 255));
        groupButton4.setText("Send Request");
        groupButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                groupButton4ActionPerformed(evt);
            }
        });

        groupButton5.setBackground(new java.awt.Color(120, 88, 161));
        groupButton5.setForeground(new java.awt.Color(255, 255, 255));
        groupButton5.setText("Send Request");
        groupButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                groupButton5ActionPerformed(evt);
            }
        });

        groupButton6.setBackground(new java.awt.Color(120, 88, 161));
        groupButton6.setForeground(new java.awt.Color(255, 255, 255));
        groupButton6.setText("Send Request");
        groupButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                groupButton6ActionPerformed(evt);
            }
        });

        groupButton7.setBackground(new java.awt.Color(120, 88, 161));
        groupButton7.setForeground(new java.awt.Color(255, 255, 255));
        groupButton7.setText("Send Request");
        groupButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                groupButton7ActionPerformed(evt);
            }
        });

        groupButton8.setBackground(new java.awt.Color(120, 88, 161));
        groupButton8.setForeground(new java.awt.Color(255, 255, 255));
        groupButton8.setText("Send Request");
        groupButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                groupButton8ActionPerformed(evt);
            }
        });

        groupButton9.setBackground(new java.awt.Color(120, 88, 161));
        groupButton9.setForeground(new java.awt.Color(255, 255, 255));
        groupButton9.setText("Send Request");
        groupButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                groupButton9ActionPerformed(evt);
            }
        });

        groupButton10.setBackground(new java.awt.Color(120, 88, 161));
        groupButton10.setForeground(new java.awt.Color(255, 255, 255));
        groupButton10.setText("Send Request");
        groupButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                groupButton10ActionPerformed(evt);
            }
        });

        groupButton11.setBackground(new java.awt.Color(120, 88, 161));
        groupButton11.setForeground(new java.awt.Color(255, 255, 255));
        groupButton11.setText("Send Request");
        groupButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                groupButton11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout otherGroupsPanelLayout = new javax.swing.GroupLayout(otherGroupsPanel);
        otherGroupsPanel.setLayout(otherGroupsPanelLayout);
        otherGroupsPanelLayout.setHorizontalGroup(
                otherGroupsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(otherGroupsPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(otherGroupsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(otherGroupsPanelLayout.createSequentialGroup()
                                                .addGroup(otherGroupsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(otherGroupsLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(otherGroupsLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(70, 70, 70)
                                                .addGroup(otherGroupsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(groupButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(groupButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGroup(otherGroupsPanelLayout.createSequentialGroup()
                                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                                                .addContainerGap())
                                        .addGroup(otherGroupsPanelLayout.createSequentialGroup()
                                                .addGroup(otherGroupsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(otherGroupsLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(otherGroupsLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(otherGroupsLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(otherGroupsLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(otherGroupsLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(otherGroupsLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                                                        .addComponent(otherGroupsLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(otherGroupsLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(otherGroupsLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(70, 70, 70)
                                                .addGroup(otherGroupsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(groupButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(groupButton6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(groupButton7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(groupButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(groupButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(groupButton8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(groupButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(groupButton10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(groupButton11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
        );
        otherGroupsPanelLayout.setVerticalGroup(
                otherGroupsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(otherGroupsPanelLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addGroup(otherGroupsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(otherGroupsLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                                        .addComponent(groupButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(otherGroupsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(otherGroupsLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(groupButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(otherGroupsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(otherGroupsLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(groupButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(otherGroupsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(otherGroupsPanelLayout.createSequentialGroup()
                                                .addComponent(otherGroupsLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(otherGroupsLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(otherGroupsLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(otherGroupsLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(4, 4, 4)
                                                .addComponent(otherGroupsLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(otherGroupsLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(otherGroupsLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(otherGroupsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(otherGroupsLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(groupButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(otherGroupsPanelLayout.createSequentialGroup()
                                                .addComponent(groupButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(groupButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(groupButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(groupButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(groupButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(groupButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(groupButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        calendarPanel.setBackground(new java.awt.Color(232, 235, 255));

        javax.swing.GroupLayout calendarPanelLayout = new javax.swing.GroupLayout(calendarPanel);
        calendarPanel.setLayout(calendarPanelLayout);
        calendarPanelLayout.setHorizontalGroup(
                calendarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 586, Short.MAX_VALUE)
        );
        calendarPanelLayout.setVerticalGroup(
                calendarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
        );

        invitationsPanel.setBackground(new java.awt.Color(232, 235, 255));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("------");

        javax.swing.GroupLayout invitationsPanelLayout = new javax.swing.GroupLayout(invitationsPanel);
        invitationsPanel.setLayout(invitationsPanelLayout);
        invitationsPanelLayout.setHorizontalGroup(
                invitationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(invitationsPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
                                .addContainerGap())
        );
        invitationsPanelLayout.setVerticalGroup(
                invitationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(invitationsPanelLayout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jLabel9)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        announcementsPanel.setBackground(new java.awt.Color(232, 235, 255));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Announcements");

        Class c = classRepository.findByClassId(319);
        List<Announcement> announcements = c.getAnnouncementList();
        String anno = "";
        if(announcements.size() > 0){
            for(int i = 0; i < announcements.size(); i++){
                anno += "\n" + announcements.get(i);
            }
        }

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText(anno);
        jScrollPane4.setViewportView(jTextArea1);

        javax.swing.GroupLayout announcementsPanelLayout = new javax.swing.GroupLayout(announcementsPanel);
        announcementsPanel.setLayout(announcementsPanelLayout);
        announcementsPanelLayout.setHorizontalGroup(
                announcementsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(announcementsPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
                                .addContainerGap())
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        announcementsPanelLayout.setVerticalGroup(
                announcementsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(announcementsPanelLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane4)
                                .addContainerGap())
        );

        deadlinesPanel.setBackground(new java.awt.Color(232, 235, 255));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Upcoming Deadlines");

        javax.swing.GroupLayout deadlinesPanelLayout = new javax.swing.GroupLayout(deadlinesPanel);
        deadlinesPanel.setLayout(deadlinesPanelLayout);
        deadlinesPanelLayout.setHorizontalGroup(
                deadlinesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(deadlinesPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(deadlinesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE))
                                .addContainerGap())
        );
        deadlinesPanelLayout.setVerticalGroup(
                deadlinesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(deadlinesPanelLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11)
                                .addContainerGap(471, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(overallProgressPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(18, 18, 18)
                                                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(projectSummaryPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(formNewGroupPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                .addComponent(calendarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(invitationsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                .addComponent(announcementsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(deadlinesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(otherGroupsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(launchDatePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(launchDatePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(overallProgressPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(otherGroupsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(formNewGroupPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(calendarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(invitationsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(projectSummaryPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(announcementsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(deadlinesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>



    //------------SEND REQUEST TO GROUPS----------------
    private void groupButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        Group g = groupRepository.findByGroupId(1);
        if(g != null) {
            if (!g.isFull()) {
                Class c = classRepository.findByClassId(currentUser.getClassId());
                currentUser.sendRequest(g);
                groupRepository.save(g);
                classRepository.save(c);
                studentRepository.save(currentUser);
                UIManager um=new UIManager();
                um.put("OptionPane.background",new Color(120, 88, 161));
                um.put("Panel.background",new Color(120, 88, 161));
                JOptionPane.showMessageDialog(null,"Request has sent!","Set Color",
                        JOptionPane.INFORMATION_MESSAGE);
            }
        }else{
            UIManager um=new UIManager();
            um.put("OptionPane.background",new Color(120, 88, 161));
            um.put("Panel.background",new Color(120, 88, 161));
            JOptionPane.showMessageDialog(null,"no such group exists","Set Color",
                    JOptionPane.INFORMATION_MESSAGE);
        }
        return;
    }

    private void groupButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        Group g = groupRepository.findByGroupId(2);
        if(g != null) {
            if (!g.isFull()) {
                Class c = classRepository.findByClassId(currentUser.getClassId());
                currentUser.sendRequest(g);
                groupRepository.save(g);
                classRepository.save(c);
                studentRepository.save(currentUser);
                UIManager um=new UIManager();
                um.put("OptionPane.background",new Color(120, 88, 161));
                um.put("Panel.background",new Color(120, 88, 161));
                JOptionPane.showMessageDialog(null,"Request has sent!","Set Color",
                        JOptionPane.INFORMATION_MESSAGE);
            }
        }
        else{
            UIManager um=new UIManager();
            um.put("OptionPane.background",new Color(120, 88, 161));
            um.put("Panel.background",new Color(120, 88, 161));
            JOptionPane.showMessageDialog(null,"no such group exists","Set Color",
                    JOptionPane.INFORMATION_MESSAGE);
        }
        return;
    }

    private void groupButton3ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        Group g = groupRepository.findByGroupId(3);
        if(g != null) {
            if (!g.isFull()) {
                Class c = classRepository.findByClassId(currentUser.getClassId());
                currentUser.sendRequest(g);
                groupRepository.save(g);
                classRepository.save(c);
                studentRepository.save(currentUser);
                UIManager um=new UIManager();
                um.put("OptionPane.background",new Color(120, 88, 161));
                um.put("Panel.background",new Color(120, 88, 161));
                JOptionPane.showMessageDialog(null,"Request has sent!","Set Color",
                        JOptionPane.INFORMATION_MESSAGE);
            }
        }else{
            UIManager um=new UIManager();
            um.put("OptionPane.background",new Color(120, 88, 161));
            um.put("Panel.background",new Color(120, 88, 161));
            JOptionPane.showMessageDialog(null,"no such group exists","Set Color",
                    JOptionPane.INFORMATION_MESSAGE);
        }
        return;
    }

    private void groupButton4ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        Group g = groupRepository.findByGroupId(4);
        if(g != null) {
            if (!g.isFull()) {
                Class c = classRepository.findByClassId(currentUser.getClassId());
                currentUser.sendRequest(g);
                groupRepository.save(g);
                classRepository.save(c);
                studentRepository.save(currentUser);
                UIManager um=new UIManager();
                um.put("OptionPane.background",new Color(120, 88, 161));
                um.put("Panel.background",new Color(120, 88, 161));
                JOptionPane.showMessageDialog(null,"Request has sent!","Set Color",
                        JOptionPane.INFORMATION_MESSAGE);
            }
        }else{
            UIManager um=new UIManager();
            um.put("OptionPane.background",new Color(120, 88, 161));
            um.put("Panel.background",new Color(120, 88, 161));
            JOptionPane.showMessageDialog(null,"no such group exists","Set Color",
                    JOptionPane.INFORMATION_MESSAGE);
        }
        return;
    }

    private void groupButton5ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        Group g = groupRepository.findByGroupId(5);
        if(g != null) {
            if (!g.isFull()) {
                Class c = classRepository.findByClassId(currentUser.getClassId());
                currentUser.sendRequest(g);
                groupRepository.save(g);
                classRepository.save(c);
                studentRepository.save(currentUser);
                UIManager um=new UIManager();
                um.put("OptionPane.background",new Color(120, 88, 161));
                um.put("Panel.background",new Color(120, 88, 161));
                JOptionPane.showMessageDialog(null,"Request has sent!","Set Color",
                        JOptionPane.INFORMATION_MESSAGE);
            }
        }else{
            UIManager um=new UIManager();
            um.put("OptionPane.background",new Color(120, 88, 161));
            um.put("Panel.background",new Color(120, 88, 161));
            JOptionPane.showMessageDialog(null,"no such group exists","Set Color",
                    JOptionPane.INFORMATION_MESSAGE);
        }
        return;
    }

    private void groupButton6ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        Group g = groupRepository.findByGroupId(6);
        if(g != null) {
            if (!g.isFull()) {
                Class c = classRepository.findByClassId(currentUser.getClassId());
                currentUser.sendRequest(g);
                groupRepository.save(g);
                classRepository.save(c);
                studentRepository.save(currentUser);
                UIManager um=new UIManager();
                um.put("OptionPane.background",new Color(120, 88, 161));
                um.put("Panel.background",new Color(120, 88, 161));
                JOptionPane.showMessageDialog(null,"Request has sent!","Set Color",
                        JOptionPane.INFORMATION_MESSAGE);
            }
        }else{
            UIManager um=new UIManager();
            um.put("OptionPane.background",new Color(120, 88, 161));
            um.put("Panel.background",new Color(120, 88, 161));
            JOptionPane.showMessageDialog(null,"no such group exists","Set Color",
                    JOptionPane.INFORMATION_MESSAGE);
        }
        return;
    }

    private void groupButton7ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        Group g = groupRepository.findByGroupId(7);
        if(g != null) {
            if (!g.isFull()) {
                Class c = classRepository.findByClassId(currentUser.getClassId());
                currentUser.sendRequest(g);
                groupRepository.save(g);
                classRepository.save(c);
                studentRepository.save(currentUser);
                UIManager um=new UIManager();
                um.put("OptionPane.background",new Color(120, 88, 161));
                um.put("Panel.background",new Color(120, 88, 161));
                JOptionPane.showMessageDialog(null,"Request has sent!","Set Color",
                        JOptionPane.INFORMATION_MESSAGE);
            }
        }else{
            UIManager um=new UIManager();
            um.put("OptionPane.background",new Color(120, 88, 161));
            um.put("Panel.background",new Color(120, 88, 161));
            JOptionPane.showMessageDialog(null,"no such group exists","Set Color",
                    JOptionPane.INFORMATION_MESSAGE);
        }
        return;
    }

    private void groupButton8ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        Group g = groupRepository.findByGroupId(8);
        if(g != null) {
            if (!g.isFull()) {
                Class c = classRepository.findByClassId(currentUser.getClassId());
                currentUser.sendRequest(g);
                groupRepository.save(g);
                classRepository.save(c);
                studentRepository.save(currentUser);
                UIManager um=new UIManager();
                um.put("OptionPane.background",new Color(120, 88, 161));
                um.put("Panel.background",new Color(120, 88, 161));
                JOptionPane.showMessageDialog(null,"Request has sent!","Set Color",
                        JOptionPane.INFORMATION_MESSAGE);
            }
        }else{
            UIManager um=new UIManager();
            um.put("OptionPane.background",new Color(120, 88, 161));
            um.put("Panel.background",new Color(120, 88, 161));
            JOptionPane.showMessageDialog(null,"no such group exists","Set Color",
                    JOptionPane.INFORMATION_MESSAGE);
        }
        return;
    }

    private void groupButton9ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        Group g = groupRepository.findByGroupId(9);
        if(g != null) {
            if (!g.isFull()) {
                Class c = classRepository.findByClassId(currentUser.getClassId());
                currentUser.sendRequest(g);
                groupRepository.save(g);
                classRepository.save(c);
                studentRepository.save(currentUser);
                UIManager um=new UIManager();
                um.put("OptionPane.background",new Color(120, 88, 161));
                um.put("Panel.background",new Color(120, 88, 161));
                JOptionPane.showMessageDialog(null,"Request has sent!","Set Color",
                        JOptionPane.INFORMATION_MESSAGE);
            }
        }else{
            UIManager um=new UIManager();
            um.put("OptionPane.background",new Color(120, 88, 161));
            um.put("Panel.background",new Color(120, 88, 161));
            JOptionPane.showMessageDialog(null,"no such group exists","Set Color",
                    JOptionPane.INFORMATION_MESSAGE);
        }
        return;
    }

    private void groupButton10ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        Group g = groupRepository.findByGroupId(10);
        if(g != null) {
            if (!g.isFull()) {
                Class c = classRepository.findByClassId(currentUser.getClassId());
                currentUser.sendRequest(g);
                groupRepository.save(g);
                classRepository.save(c);
                studentRepository.save(currentUser);
                UIManager um=new UIManager();
                um.put("OptionPane.background",new Color(120, 88, 161));
                um.put("Panel.background",new Color(120, 88, 161));
                JOptionPane.showMessageDialog(null,"Request has sent!","Set Color",
                        JOptionPane.INFORMATION_MESSAGE);
            }
        }else{
            UIManager um=new UIManager();
            um.put("OptionPane.background",new Color(120, 88, 161));
            um.put("Panel.background",new Color(120, 88, 161));
            JOptionPane.showMessageDialog(null,"no such group exists","Set Color",
                    JOptionPane.INFORMATION_MESSAGE);
        }
        return;
    }

    private void groupButton11ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        Group g = groupRepository.findByGroupId(11);
        if(g != null) {
            if (!g.isFull()) {
                Class c = classRepository.findByClassId(currentUser.getClassId());
                currentUser.sendRequest(g);
                groupRepository.save(g);
                classRepository.save(c);
                studentRepository.save(currentUser);
                UIManager um=new UIManager();
                um.put("OptionPane.background",new Color(120, 88, 161));
                um.put("Panel.background",new Color(120, 88, 161));
                JOptionPane.showMessageDialog(null,"Request has sent!","Set Color",
                        JOptionPane.INFORMATION_MESSAGE);
            }
        }else{
            UIManager um=new UIManager();
            um.put("OptionPane.background",new Color(120, 88, 161));
            um.put("Panel.background",new Color(120, 88, 161));
            JOptionPane.showMessageDialog(null,"no such group exists","Set Color",
                    JOptionPane.INFORMATION_MESSAGE);
        }
        return;
    }

    //--------------------------------FORM NEW GROUP BUTTON--------------------------------
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        //System.out.println(currentUser);
        Class c = classRepository.findByClassId(currentUser.getClassId());
        Group g = currentUser.formAGroup(c.assignGroupId(), c.getProject().getMaxGroupSize());
        g.setClassId(currentUser.getClassId());
        c.addGroupId(g.getGroupId());

        //Set group according to class
        g.setGroupAssignmentList(c.getProject().getAssignmentList());
        g.setAnnouncementList(c.getAnnouncementList());

        groupRepository.save(g);
        classRepository.save(c);
        studentRepository.save(currentUser);

        return;
    }

    // Variables declaration - do not modify
    private javax.swing.JPanel announcementsPanel;
    private javax.swing.JPanel calendarPanel;
    private javax.swing.JPanel deadlinesPanel;
    private javax.swing.JPanel formNewGroupPanel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JPanel invitationsPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel launchDatePanel;
    private javax.swing.JPanel otherGroupsPanel;
    private javax.swing.JPanel overallProgressPanel;
    private javax.swing.JPanel projectSummaryPanel;
    private javax.swing.JLabel otherGroupsLabel1;
    private javax.swing.JLabel otherGroupsLabel10;
    private javax.swing.JLabel otherGroupsLabel11;
    private javax.swing.JLabel otherGroupsLabel2;
    private javax.swing.JLabel otherGroupsLabel3;
    private javax.swing.JLabel otherGroupsLabel4;
    private javax.swing.JLabel otherGroupsLabel5;
    private javax.swing.JLabel otherGroupsLabel6;
    private javax.swing.JLabel otherGroupsLabel7;
    private javax.swing.JLabel otherGroupsLabel8;
    private javax.swing.JLabel otherGroupsLabel9;
    private javax.swing.JButton groupButton1;
    private javax.swing.JButton groupButton10;
    private javax.swing.JButton groupButton11;
    private javax.swing.JButton groupButton2;
    private javax.swing.JButton groupButton3;
    private javax.swing.JButton groupButton4;
    private javax.swing.JButton groupButton5;
    private javax.swing.JButton groupButton6;
    private javax.swing.JButton groupButton7;
    private javax.swing.JButton groupButton8;
    private javax.swing.JButton groupButton9;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration
}

